package main

import (
	"math/rand"
)

type Monster struct {
	Name  string
	Type  string
	Count int
	CR    int
}

type MonsterData struct {
	Name string
	CR   int
}

func getMonsterCategoryForRoom(rtype RoomType, env DungeonEnvironment) string {
	if env == "Alien" {
		return "Aberration"
	}
	if env == "Elemental" {
		return "Elemental"
	}
	if env == "Planar" {
		return "Outsider"
	}

	switch rtype {
	case "Crypt", "Reliquary":
		return "Undead"
	case "Guard Room", "Barracks", "Armory":
		return "Humanoid"
	case "Prison Block", "Torture Chamber":
		return "Monstrous Humanoid"
	case "Temple":
		return "Outsider"
	case "Main Vault":
		return "Construct"
	case "Maze", "Hidden Chamber":
		return "Ooze"
	case "Living Quarters", "Kitchen", "Common Area":
		return "Humanoid"
	default:
		return "Animal"
	}
}

var monsterDatabase = map[string][]MonsterData{
	"Aberration": {
		{"Mind Leach", 0}, {"Psionic Sinew", 0}, {"Neogi, Spawn", 0}, {"Cerebral Hood", 0}, {"Dolgrim", 1},
		{"Flumph", 1}, {"Howler Wasp", 1}, {"Ixitxachitl", 1}, {"Living Breastplate", 1}, {"Mindshreadder Larva", 1},
		{"Overseer", 1}, {"Tentacle Whip", 1}, {"Tongueworm", 1}, {"Anguillian", 2}, {"Choker", 2},
		{"Dolgaunt", 2}, {"Illithocyte", 2}, {"Lurking Stranglers", 2}, {"Mad Slasher", 2}, {"Mazchedeen", 2},
		{"Skum", 2}, {"Ustilagor", 2}, {"Curse Cold One", 3}, {"Dustblight", 3}, {"Ethereal Filcher", 3},
		{"Ettercap", 3}, {"Fihyr", 3}, {"Grell", 3}, {"Grick", 3}, {"Ixitxachitl, Vampiric", 3},
		{"Lurker", 3}, {"Meenlock", 3}, {"Runehound", 3}, {"Rust Monster", 3}, {"Carrion Crawler", 4},
		{"Choker, Obah-Blessed", 4}, {"Half-Illithid Lizardfolk", 4}, {"Harpoon Spider", 4}, {"Mimic", 4}, {"Mindshreadder Warrior", 4},
		{"Neogi, Adult", 4}, {"Otyugh", 4}, {"Snowcloak", 4}, {"Cloaker", 5}, {"Gibbering Mouther", 5},
		{"Howler Wasp Queen", 5}, {"Ineffable Horror", 5}, {"Morkoth", 5}, {"Psurlon, Average", 5}, {"Quaraphon", 5},
		{"Wyste", 5}, {"Ahuizotl", 6}, {"Arachnoid Mouther", 6}, {"Catoblepas", 6}, {"Chuul, Slime", 6},
		{"Dolgaunt, Monk 4th", 6}, {"Gauth", 6}, {"Hook Horror", 6}, {"Mageripper Swarm", 6}, {"Octopin", 6},
		{"Rot Reaver", 6}, {"Will-O-Wisp", 6}, {"Aboleth", 7}, {"Chuul", 7}, {"Darktentacles", 7},
		{"Drider", 7}, {"Ettin, Hivebrood", 7}, {"Ettin, Spellwarped", 7}, {"Malasynep", 7}, {"Naga, Water", 7},
		{"Phasm", 7}, {"Seryulin", 7}, {"Slasrath", 7}, {"Squamous Spewer", 7}, {"Stonesinger", 7},
		{"Susurrus", 7}, {"Umber Hulk", 7}, {"Zern Arcanovoure", 7}, {"Athach", 8}, {"Destrachan", 8},
		{"Mind Flayer", 8}, {"Mindshreadder Zenthal", 8}, {"Naga, Dark", 8}, {"Otyugh, Lifelech", 8}, {"Rust Monster, Advanced", 8},
		{"Athach, Anarchic", 9}, {"Chwidencha", 9}, {"Delver", 9}, {"Dharculus", 9}, {"Ethergaunt, Red", 9},
		{"Harpoon Spider, Dread", 9}, {"Lodestone Marauder", 9}, {"Naga, Spirit", 9}, {"Psurlon, Elder", 9}, {"Roper, Prismatic", 9},
		{"Rukanyr", 9}, {"Avolakia", 10}, {"Balhannoth", 10}, {"Darkweaver", 10}, {"Malasynep Mindmage", 10},
		{"Naga, Guardian", 10}, {"Nerve Swimmers", 10}, {"Quarapohon Bully", 10}, {"Seryulin, Greater", 10}, {"Shrieking Terror, 5 Headed", 10},
		{"Gaj", 11}, {"Naga, Worm", 11}, {"Phiuhl", 11}, {"Julajimus", 12}, {"Necrothane", 12},
		{"Ocularon", 12}, {"Skybleeder", 12}, {"Beholder", 13}, {"Ethergaunt, White", 13}, {"Froghemoth", 13},
		{"Shrieking Terror, 10 Headed", 13}, {"Odopi", 14}, {"Umber Hulk, Truly Horrid", 14}, {"Annihilator", 15}, {"Fihyr, Great", 15},
		{"Psurlon, Giant", 15}, {"Thessalhydra", 15}, {"Tunnel Terror", 15}, {"Windghost", 15}, {"Abyssal Ant Swarm", 16},
		{"Beholder, Half-Illithid", 16}, {"Moonbeast", 16}, {"Aboleth Mage", 17}, {"Ethergaunt, Black", 17}, {"Maulgoth", 17},
		{"Mind Flayer, Sorcerer 9th", 17}, {"Mind Worm", 17}, {"Spectral Lurker", 17}, {"Chilblain", 18}, {"Odopi, Elder", 18},
		{"Yuan-Ti Anathema", 18}, {"Mother Worm", 20}, {"Shivhad", 21}, {"Elder Brain", 25},
	},
	"Animal": {
		{"Bat", 0}, {"Toad", 0}, {"Rat", 0}, {"Donkey", 0}, {"Lizard", 0}, {"Monkey", 0}, {"Penguin", 0}, {"Ramphor", 0},
		{"Raven", 0}, {"Albatross", 0}, {"Cat", 0}, {"Critic Lizard", 0}, {"Dinosaur, Rhamphorhynchus", 0}, {"Fox, Arctic", 0},
		{"Horned Lizard", 0}, {"Otter", 0}, {"Owl", 0}, {"Pony", 0}, {"Squirrel, Flying", 0}, {"Weasel", 0}, {"Caribou", 0},
		{"Dire Rat", 0}, {"Dog", 0}, {"Hawk", 0}, {"Jankx", 0}, {"Kes'trekel", 0}, {"Otter, Sea", 0}, {"Sea Snake, Viper, Tiny", 0},
		{"Seal", 0}, {"Snake, Viper, Tiny", 0}, {"Stingray", 0}, {"Vulture", 0}, {"Baboon", 0}, {"Badger", 0}, {"Barracuda", 0},
		{"Carcass Eater", 0}, {"Chordevoc", 0}, {"Dinosaur, Compsognathus", 0}, {"Dinosaur, Leaellynasaura", 0}, {"Dinosaur, Troodon", 0},
		{"Eagle", 0}, {"Eel", 0}, {"Pony, War", 0}, {"Porpoise", 0}, {"Sea Snake, Viper, Small", 0}, {"Snake, Viper, Small", 0},
		{"Yallix", 0}, {"Z'Tal", 0}, {"Baazrag", 1}, {"Brixashulty", 1}, {"Camel", 1}, {"Camel, Dromedary", 1},
		{"Camel, Two-Humped", 1}, {"Dinosaur, Swindlespitter", 1}, {"Dog, Riding", 1}, {"Heavy Horse, Magebred", 1}, {"Horse, Heavy", 1},
		{"Horse, Light", 1}, {"Horse, Valenar Riding", 1}, {"Hyena", 1}, {"Manta Ray", 1}, {"Moose", 1}, {"Moray Eel", 1},
		{"Mule", 1}, {"Octopus", 1}, {"Rat, Horrid", 1}, {"Sea Snake, Viper, Medium", 1}, {"Seahorse, Giant", 1}, {"Seal Lion", 1},
		{"Serval", 1}, {"Shark, Medium", 1}, {"Snake, Viper, Medium", 1}, {"Squid", 1}, {"Taga rivvin", 1}, {"Turtle, Snapping", 1},
		{"Warhorse, Light", 1}, {"Wolf", 1}, {"Ape", 2}, {"Bat Swarm", 2}, {"Bear, Black", 2}, {"Bison", 2}, {"Boar", 2},
		{"Camel, War", 2}, {"Cheetah", 2}, {"Crocodile", 2}, {"Dekayi", 2}, {"Dinosaur, Dimetrodon", 2}, {"Dinosaur, Fleshraker", 2},
		{"Dinosaur, Pteranodon", 2}, {"Dinosaur, Velociraptor", 2}, {"Dire Badger", 2}, {"Dire Bat", 2}, {"Dire Hawk", 2},
		{"Dire Jackal", 2}, {"Dire Weasel", 2}, {"Elk", 2}, {"Erdlu", 2}, {"Horse, Scorned", 2}, {"Kank", 2},
		{"Komodo Dragon", 2}, {"Leopard", 2}, {"Lizard, Monitor", 2}, {"Rat Swarm", 2}, {"Riding Bird", 2},
		{"Riding Bird, Black", 2}, {"Sailsnake", 2}, {"Sea Snake, Viper, Large", 2}, {"Seskarran", 2}, {"Shark, Large", 2},
		{"Snake, Constrictor", 2}, {"Snake, Viper, Large", 2}, {"Walrus", 2}, {"Warhorse, Heavy", 2}, {"Wolverine", 2},
		{"Crodlu", 3}, {"Desmodu Guard Bat", 3}, {"Desmodu Hunting Bat", 3}, {"Dinosaur, Cryptoclidus", 3}, {"Dinosaur, Deinonychus", 3},
		{"Dinosaur, Protoceratops", 3}, {"Dinosaur, Pteranodon", 3}, {"Dire Ape", 3}, {"Dire Eagle", 3}, {"Dire Eel", 3},
		{"Dire Toad", 3}, {"Dire Vulture", 3}, {"Dire Wolf", 3}, {"Jhaker", 3}, {"Killer Frog", 3}, {"Lion", 3},
		{"Pterrax", 3}, {"Sea Snake, Viper, Huge", 3}, {"Snake, Viper, Huge", 3}, {"Viper Swarm", 3}, {"Ape, Horrid", 4},
		{"Ape, Snow", 4}, {"Baazrag, Boneclaw", 4}, {"Bear, Brown", 4}, {"Bear, Polar", 4}, {"Crocodile, Giant", 4},
		{"Dire Barracuda", 4}, {"Dire Boar", 4}, {"Dire Horse", 4}, {"Dire Puma", 4}, {"Dire Wolverine", 4}, {"Jagendar", 4},
		{"Megaloceros", 4}, {"Piranha Swarm", 4}, {"Razorwing", 4}, {"Rhinoceros", 4}, {"Shark, Huge", 4}, {"Terror Bird", 4},
		{"Tiger", 4}, {"Woodling Monitor Lizard", 4}, {"Cilops", 5}, {"Crodlu, Heavy", 5}, {"Desmodu War Bat", 5},
		{"Dinosaur, Dipotodon", 5}, {"Dinosaur, Helicoprion", 5}, {"Dire Lion", 5}, {"Dire Snake", 5}, {"Elephant Seal", 5},
		{"Gar, Giant", 5}, {"Glyptodon", 5}, {"Inix", 5}, {"Rhinoceros, Warbeast", 5}, {"Smilodon", 5},
		{"Snake, Constrictor, Giant", 5}, {"Whale, Orca", 5}, {"Dinosaur, Bloodstriker", 6}, {"Dinosaur, Ichthyosaur", 6},
		{"Dinosaur, Megaraptor", 6}, {"Dinosaur, Pachycephalosaurus", 6}, {"Hippopotamus", 6}, {"Legendary Eagle", 6},
		{"Needletooth Swarm", 6}, {"Sea Tiger", 6}, {"Whale, Baleen", 6}, {"Dinosaur, Allosaurus", 7}, {"Dinosaur, Ankylosaurus", 7},
		{"Dinosaur, Elasosaurus", 7}, {"Dinosaur, Elgonn", 7}, {"Dinosaur, Parasaurolophus", 7}, {"Dire Bear", 7}, {"Dire Elk", 7},
		{"Dire Toad, Advanced", 7}, {"Elephant", 7}, {"Lizard Giant Banded", 7}, {"Legendary Ape", 7}, {"Legendary Wolf", 7},
		{"Mekillot", 7}, {"Whale, Cachalot", 7}, {"Dinosaur, Archelon", 8}, {"Dinosaur, Quetzalcoatus", 8}, {"Dinosaur, Tyrannosaurus", 8},
		{"Dire Tiger", 8}, {"Dire Tortoise", 8}, {"Legendary Horse", 8}, {"Legendary Snake", 8}, {"Mastryial", 8},
		{"Megatherium", 8}, {"Octopus, Giant", 8}, {"Bilge Eel", 9}, {"Dinosaur, Indriothere", 9}, {"Dinosaur, Triceratops", 9},
		{"Dire Rhinoceros", 9}, {"Dire Shark", 9}, {"Fhorge", 9}, {"Legendary Bear", 9}, {"Mastodon", 9}, {"Roc", 9},
		{"Squid, Giant", 9}, {"Woolly Mammoth", 9}, {"Zeuglodon", 9}, {"Dinosaur, Mosasaur", 10}, {"Dinosaur, Plesiosaur", 10},
		{"Dinosaur, Stegosaurus", 10}, {"Dire Elephant", 10}, {"Legendary Shark", 10}, {"Legendary Tiger", 10}, {"Dire Polar Bear", 11},
		{"Forest Sloth", 11}, {"Magalodon", 11}, {"Dinosaur, Diplodocus", 12}, {"Dinosaur, Seismosaurus", 12}, {"Dinosaur, Giganotosaurus", 13},
		{"Dinosaur, Spinosaurus", 13}, {"Grizzly Mastodon", 13}, {"Toad, Titanic", 13}, {"Dire Hippopotamus", 14},
		{"Dinosaur, Liopleurodon", 15}, {"Dinosaur, Battletitan", 16},
	},
	"Construct": {
		{"Animated Object, Fine", 0}, {"Jumping Caltrop", 0}, {"Expeditious Messenger", 0}, {"Animated Object, Tiny", 0},
		{"Clockwork Mender", 0}, {"Copper Asp", 0}, {"Dedicated Wright", 0}, {"Furtive Filcher", 0}, {"Razor Hawk", 0},
		{"Warforged", 0}, {"Warforged Scout", 0}, {"Animated Object, Small", 1}, {"Bogun", 1}, {"Clockroach", 1},
		{"Crystal Cat", 1}, {"Glass Dragonfly", 1}, {"Golem, Paper", 1}, {"Homunculus", 1}, {"Iron Defender", 1},
		{"Mercurial Spider", 1}, {"Raggamoffyn, Tatterdemanimal", 1}, {"Salvage Rat", 1}, {"Animated Object, Medium", 2},
		{"Erudite Owl", 2}, {"Golem, Wax", 2}, {"Iron Cobra", 2}, {"Necrophidius", 2}, {"Animated Object, Large", 3},
		{"Carrionette", 3}, {"Clockwork Mender Swarm", 3}, {"Clockwork Pony", 3}, {"Clockwork Stallion", 3}, {"Dread Guard", 3},
		{"Flying Fingers", 3}, {"Gargoyle, Ice Beast", 3}, {"Golem, Tin", 3}, {"Golem, Wood", 3}, {"Maug", 3},
		{"Raggamoffyn, Common", 3}, {"Spark Guardian", 3}, {"Captured Bugbear", 4}, {"Clockwork Eunuch", 4},
		{"Clockwork Horror, Electrum", 4}, {"Gauntlet Guardian", 4}, {"Golem, Fungus", 4}, {"Half-Golem, Clay", 4},
		{"Half-Golem, Flesh", 4}, {"Half-Golem, Iron", 4}, {"Half-Golem, Stone", 4}, {"Hammerer", 4}, {"Necromancer Knuckles", 4},
		{"Pulverizer", 4}, {"Animated Object, Huge", 5}, {"Brass Man", 5}, {"Clockwork Horror, Gold", 5}, {"Golem, Chain", 5},
		{"Golem, Junk", 5}, {"Golem, Stained Glass", 5}, {"Raggamoffyn, Guttersnipe", 5}, {"Warforged Charger", 5},
		{"Bladed Guardian", 6}, {"Caryatid Column", 6}, {"Dire Lion, Effigy", 6}, {"Golem, Fang", 6}, {"Golem, Maggot", 6},
		{"Animated Object, Gargantuan", 7}, {"Clockwork Horror, Platinum", 7}, {"Golem, Flesh", 7}, {"Golem, Gloom", 7},
		{"Golem, Web", 7}, {"Nimblewright", 7}, {"Quesar", 7}, {"Raggamoffyn, Shrapnyl", 7}, {"Blood Golem of Hextor", 8},
		{"Golem, Rune", 8}, {"Shield Guardian", 8}, {"Shreadstorm", 8}, {"Warforged Titan", 8}, {"Clockwork Horror, Adamantine", 9},
		{"Eidolon, Rogue", 9}, {"Giant Banded Lizard Dustform", 9}, {"Golem, Coral", 9}, {"Golem, Grave Dirt", 9},
		{"Golem, Ice", 9}, {"Golem, Relief", 9}, {"Golem, Swarm", 9}, {"Inevitable, Zelekhut", 9}, {"Waste Crawler", 9},
		{"Animated Object, Colossal", 10}, {"Bronze Serpent", 10}, {"Golem, Brain", 10}, {"Golem, Brass", 10},
		{"Golem, Clay", 10}, {"Runic Guardian", 10}, {"Death Hurler", 11}, {"Golem, Alchemical", 11}, {"Golem, Mud", 11},
		{"Golem, Shadesteel", 11}, {"Golem, Stone", 11}, {"Juggernaut", 11}, {"Retriever", 11}, {"Wicker Man", 11},
		{"Cadaver Collector", 12}, {"Golem, Clay, Obah-Blessed", 12}, {"Golem, Dragonbone", 12}, {"Golem, Ice Advanced", 12},
		{"Golem, Sand", 12}, {"Golem, Stone Advanced", 12}, {"Inevitable, Kolyarut", 12}, {"Slaughterstone Eviscerator", 12},
		{"Golem, Dragonflesh", 13}, {"Golem, Hangman", 13}, {"Golem, Iron", 13}, {"Golem, Tombstone", 13},
		{"Golem, Black Ice", 14}, {"Golem, Shadesteel Greater", 14}, {"Guardian Ship", 14}, {"Golem, Drakestone", 15},
		{"Grisgol", 15}, {"Inevitable, Marut", 15}, {"Slaughterstone Behemoth", 15}, {"Golem, Stone Greater", 16},
		{"Zodar", 16}, {"Bronze Locust Swarm", 17}, {"Cadaver Collector, Greater", 17}, {"Golem, Hellfire", 17},
		{"Golem, Ironwyrm", 17}, {"Inevitable, Quarut", 17}, {"Blackstone Gigant", 18}, {"Golem, Demonflesh", 18},
		{"Golem, Prismatic", 18}, {"Golem, Tombstone Greater", 18}, {"Juggernaut, Seven-Headed", 18},
		{"Primordial Colossus", 18}, {"Inevitable, Varakhut", 19}, {"Inevitable, Marut, Advanced", 22},
	},
	"Deathless": {
		{"Undying Soldier", 2}, {"Undying Wizard", 2}, {"Sacred Watcher, Human Fighter 5th", 7},
		{"Crypt Warden", 8}, {"Undying Councilor", 9}, {"Ascendant Councilor", 18},
	},
	"Dragon": {
		{"Felldrake, Crested", 1}, {"Pseudodragon", 1}, {"Fang Dragon, Wyrmling", 2}, {"Felldrake, Spitting", 2},
		{"Sand Dragon, Wyrmling", 2}, {"Spiked Sea Serpent, Wyrmling", 2}, {"Spinewyrm, Wyrmling", 2},
		{"Steel Dragon, Wyrmling", 2}, {"White Dragon, Wyrmling", 2}, {"Arboreal Dragon, Wyrmling", 3},
		{"Astral Dragon, Wyrmling", 3}, {"Battle Dragon, Wyrmling", 3}, {"Beast Dragon, Wyrmling", 3},
		{"Black Dragon, Wyrmling", 3}, {"Blue Dragon, Wyrmling", 3}, {"Brass Dragon, Wyrmling", 3},
		{"Bronze Dragon, Wyrmling", 3}, {"Chaos Dragon, Wyrmling", 3}, {"Concordant Dragon, Wyrmling", 3},
		{"Copper Dragon, Wyrmling", 3}, {"Crested Sea Serpent, Wyrmling", 3}, {"Crystal Dragon, Wyrmling", 3},
		{"Dracotaur", 3}, {"Elysian Dragon, Wyrmling", 3}, {"Emerald Dragon, Wyrmling", 3}, {"Ethereal Dragon, Wyrmling", 3},
		{"Fang Dragon, Very Young", 3}, {"Felldrake, Horned", 3}, {"Gloom Dragon, Wyrmling", 3}, {"Green Dragon, Wyrmling", 3},
		{"Hex Dragon, Wyrmling", 3}, {"Mercury Dragon, Wyrmling", 3}, {"Mist Dragon, Wyrmling", 3},
		{"Rust Dragon, Wyrmling", 3}, {"Sand Dragon, Very Young", 3}, {"Sapphire Dragon, Wyrmling", 3},
		{"Shadow Dragon, Wyrmling", 3}, {"Spinewyrm, Very Young", 3}, {"Styx Dragon, Wyrmling", 3},
		{"Tome Dragon, Wyrmling", 3}, {"White Dragon, Very Young", 3}, {"Amethyst Dragon, Wyrmling", 4},
		{"Axial Dragon, Wyrmling", 4}, {"Battle Dragon, Very Young", 4}, {"Black Dragon, Very Young", 4},
		{"Blue Dragon, Very Young", 4}, {"Brainstealer Dragon, Wyrmling", 4}, {"Brass Dragon, Very Young", 4},
		{"Chaos Dragon, Very Young", 4}, {"Chole Dragon, Wyrmling", 4}, {"Crested Sea Serpent, Very Young", 4},
		{"Crystal Dragon, Very Young", 4}, {"Dragonnel", 4}, {"Drake, Stone", 4}, {"Elysian Dragon, Very Young", 4},
		{"Ethereal Dragon, Very Young", 4}, {"Fang Dragon, Young", 4}, {"Felldrake, Spiked", 4},
		{"Gloom Dragon, Very Young", 4}, {"Grayhawk Dragon, Wyrmling", 4}, {"Green Dragon, Very Young", 4},
		{"Hex Dragon, Very Young", 4}, {"Lantern Sea Serpent, Wyrmling", 4}, {"Mercury Dragon, Very Young", 4},
		{"Mist Dragon, Very Young", 4}, {"Oceanus Dragon, Wyrmling", 4}, {"Pyroclastic Dragon, Wyrmling", 4},
		{"Red Dragon, Wyrmling", 4}, {"Rust Dragon, Very Young", 4}, {"Shadow Dragon, Very Young", 4},
		{"Silver Dragon, Wyrmling", 4}, {"Spiked Sea Serpent, Very Young", 4}, {"Steel Dragon, Very Young", 4},
		{"Styx Dragon, Very Young", 4}, {"Topaz Dragon, Wyrmling", 4}, {"White Dragon, Young", 4},
		{"Amethyst Dragon, Very Young", 5}, {"Arboreal Dragon, Very Young", 5}, {"Astral Dragon, Very Young", 5},
		{"Axial Dragon, Very Young", 5}, {"Beast Dragon, Very Young", 5}, {"Black Dragon, Young", 5},
		{"Bronze Dragon, Very Young", 5}, {"Chole Dragon, Very Young", 5}, {"Concordant Dragon, Very Young", 5},
		{"Copper Dragon, Very Young", 5}, {"Crested Sea Serpent, Young", 5}, {"Crystal Dragon, Young", 5},
		{"Drake, Ambush", 5}, {"Drake, Portal", 5}, {"Emerald Dragon, Very Young", 5}, {"Gold Dragon, Wyrmling", 5},
		{"Grayhawk Dragon, Very Young", 5}, {"Howling Dragon, Wyrmling", 5}, {"Lantern Sea Serpent, Very Young", 5},
		{"Mercury Dragon, Young", 5}, {"Mist Dragon, Young", 5}, {"Oceanus Dragon, Very Young", 5},
		{"Pyroclastic Dragon, Very Young", 5}, {"Radiant Dragon, Wyrmling", 5}, {"Red Dragon, Very Young", 5},
		{"Sand Dragon, Young", 5}, {"Sapphire Dragon, Very Young", 5}, {"Silver Dragon, Very Young", 5},
		{"Spiked Sea Serpent, Young", 5}, {"Spinewyrm, Young", 5}, {"Steel Dragon, Juvenile", 5},
		{"Tarterian Dragon, Wyrmling", 5}, {"Tome Dragon, Very Young", 6}, {"Topaz Dragon, Very Young", 6},
		{"Adamantine Dragon, Wyrmling", 6}, {"Arboreal Dragon, Young", 6}, {"Astral Dragon, Young", 6},
		{"Battle Dragon, Young", 6}, {"Blue Dragon, Young", 6}, {"Brainstealer Dragon, Very Young", 6},
		{"Brass Dragon, Young", 6}, {"Chaos Dragon, Young", 6}, {"Drake, Air", 6}, {"Elysian Dragon, Young", 6},
		{"Ethereal Dragon, Young", 6}, {"Faerie Dragon", 6}, {"Fang Dragon, Juvenile", 6}, {"Gloom Dragon, Young", 6},
		{"Grayhawk Dragon, Young", 6}, {"Green Dragon, Young", 6}, {"Half-Black Dragon Human Fighter", 6},
		{"Hex Dragon, Young", 6}, {"Howling Dragon, Very Young", 6}, {"Landwyrm, Plains", 6},
		{"Mercury Dragon, Juvenile", 6}, {"Mist Dragon, Juvenile", 6}, {"Oceanus Dragon, Young", 6},
		{"Pyroclastic Dragon, Young", 6}, {"Radiant Dragon, Very Young", 6}, {"Rust Dragon, Young", 6},
		{"Sanctified Young Red Dragon", 6}, {"Shadow Dragon, Young", 6}, {"Styx Dragon, Young", 6},
		{"Tarterian Dragon, Very Young", 6}, {"White Dragon, Juvenile", 6}, {"Wyvern", 6},
		{"Amethyst Dragon, Young", 7}, {"Beast Dragon, Young", 7}, {"Black Dragon, Juvenile", 7},
		{"Bronze Dragon, Young", 7}, {"Chole Dragon, Young", 7}, {"Concordant Dragon, Young", 7},
		{"Copper Dragon, Young", 7}, {"Crested Sea Serpent, Juvenile", 7}, {"Dracotaur Rager", 7},
		{"Drake, Ice", 7}, {"Emerald Dragon, Young", 7}, {"Ethereal Dragon, Juvenile", 7},
		{"Gold Dragon, Very Young", 7}, {"Lantern Sea Serpent, Young", 7}, {"Red Dragon, Young", 7},
		{"Sand Dragon, Juvenile", 7}, {"Sapphire Dragon, Young", 7}, {"Silver Dragon, Young", 7},
		{"Spiked Sea Serpent, Juvenile", 7}, {"Steel Dragon, Young Adult", 7}, {"Tome Dragon, Young", 7},
		{"Topaz Dragon, Young", 7}, {"Adamantine Dragon, Very Young", 8}, {"Astral Dragon, Juvenile", 8},
		{"Axial Dragon, Young", 8}, {"Battle Dragon, Juvenile", 8}, {"Blue Dragon, Juvenile", 8},
		{"Brass Dragon, Juvenile", 8}, {"Chaos Dragon, Juvenile", 8}, {"Crested Sea Serpent, Young Adult", 8},
		{"Crystal Dragon, Juvenile", 8}, {"Drake, Water", 8}, {"Elysian Dragon, Juvenile", 8},
		{"Fang Dragon, Young Adult", 8}, {"Gloom Dragon, Juvenile", 8}, {"Grayhawk Dragon, Juvenile", 8},
		{"Green Dragon, Juvenile", 8}, {"Hex Dragon, Juvenile", 8}, {"Howling Dragon, Young", 8},
		{"Landwyrm, Underdark", 8}, {"Lantern Sea Serpent, Juvenile", 8}, {"Mercury Dragon, Young Adult", 8},
		{"Mist Dragon, Young Adult", 8}, {"Radiant Dragon, Young", 8}, {"Rust Dragon, Juvenile", 8},
		{"Shadow Dragon, Juvenile", 8}, {"Spinewyrm, Juvenile", 8}, {"Steel Dragon, Adult", 8},
		{"Styx Dragon, Juvenile", 8}, {"Tarterian Dragon, Young", 8}, {"White Dragon, Young Adult", 8},
		{"Amethyst Dragon, Juvenile", 9}, {"Arboreal Dragon, Juvenile", 9}, {"Beast Dragon, Juvenile", 9},
		{"Black Dragon, Young Adult", 9}, {"Brainstealer Dragon, Young", 9}, {"Bronze Dragon, Juvenile", 9},
		{"Chole Dragon, Juvenile", 9}, {"Copper Dragon, Juvenile", 9}, {"Dragon Turtle", 9}, {"Drake, Rage", 9},
		{"Drake, Smoke", 9}, {"Emerald Dragon, Juvenile", 9}, {"Ethereal Dragon, Young Adult", 9},
		{"Gold Dragon, Young", 9}, {"Oceanus Dragon, Juvenile", 9}, {"Pyroclastic Dragon, Juvenile", 9},
		{"Remorhaz, Half-White Dragon", 9}, {"Sand Dragon, Young Adult", 9}, {"Sapphire Dragon, Juvenile", 9},
		{"Spiked Sea Serpent, Young Adult", 9}, {"Spinewyrm, Young Adult", 9}, {"Wardrake", 9},
		{"Adamantine Dragon, Young", 10}, {"Axial Dragon, Juvenile", 10}, {"Battle Dragon, Young Adult", 10},
		{"Brainstealer Dragon, Juvenile", 10}, {"Brass Dragon, Young Adult", 10}, {"Concordant Dragon, Juvenile", 10},
		{"Drake, Fire", 10}, {"Elysian Dragon, Young Adult", 10}, {"Ethereal Dragon, Adult", 10},
		{"Fang Dragon, Adult", 10}, {"Gloom Dragon, Young Adult", 10}, {"Grayhawk Dragon, Young Adult", 10},
		{"Hex Dragon, Young Adult", 10}, {"Howling Dragon, Juvenile", 10}, {"Landwyrm, Forest", 10},
		{"Lantern Sea Serpent, Young Adult", 10}, {"Mercury Dragon, Adult", 10}, {"Mist Dragon, Adult", 10},
		{"Radiant Dragon, Juvenile", 10}, {"Red Dragon, Juvenile", 10}, {"Silver Dragon, Juvenile", 10},
		{"Ssvaklor", 10}, {"Styx Dragon, Young Adult", 10}, {"Tarterian Dragon, Juvenile", 10},
		{"Tome Dragon, Juvenile", 10}, {"Topaz Dragon, Juvenile", 10}, {"White Dragon, Adult", 10},
		{"Astral Dragon, Young Adult", 11}, {"Black Dragon, Adult", 11}, {"Blue Dragon, Young Adult", 11},
		{"Chaos Dragon, Young Adult", 11}, {"Copper Dragon, Young Adult", 11}, {"Crested Sea Serpent, Adult", 11},
		{"Crystal Dragon, Young Adult", 11}, {"Dragon Eel", 11}, {"Drake, Earth", 11}, {"Gold Dragon, Juvenile", 11},
		{"Green Dragon, Young Adult", 11}, {"Rust Dragon, Young Adult", 11}, {"Sapphire Dragon, Young Adult", 11},
		{"Shadow Dragon, Young Adult", 11}, {"Spiked Sea Serpent, Adult", 11}, {"Spinewyrm, Adult", 11},
		{"Steel Dragon, Mature Adult", 11}, {"Adamantine Dragon, Juvenile", 12}, {"Amethyst Dragon, Young Adult", 12},
		{"Arboreal Dragon, Young Adult", 12}, {"Battle Dragon, Adult", 12}, {"Beast Dragon, Young Adult", 12},
		{"Brainstealer Dragon, Young Adult", 12}, {"Brass Dragon, Adult", 12}, {"Bronze Dragon, Young Adult", 12},
		{"Chole Dragon, Young Adult", 12}, {"Concordant Dragon, Young Adult", 12}, {"Drake, Ooze", 12},
		{"Elysian Dragon, Adult", 12}, {"Emerald Dragon, Young Adult", 12}, {"Fang Dragon, Mature Adult", 12},
		{"Gloom Dragon, Adult", 12}, {"Grayhawk Dragon, Adult", 12}, {"Hex Dragon, Adult", 12},
		{"Landwyrm, Hill", 12}, {"Lantern Sea Serpent, Adult", 12}, {"Mercury Dragon, Mature Adult", 12},
		{"Mist Dragon, Mature Adult", 12}, {"Oceanus Dragon, Young Adult", 12}, {"Pyroclastic Dragon, Young Adult", 12},
		{"Sand Dragon, Adult", 12}, {"Steel Dragon, Old", 12}, {"Styx Dragon, Adult", 12},
		{"White Dragon, Mature Adult", 12}, {"Arboreal Dragon, Adult", 13}, {"Astral Dragon, Adult", 13},
		{"Axial Dragon, Young Adult", 13}, {"Chaos Dragon, Adult", 13}, {"Crested Sea Serpent, Mature Adult", 13},
		{"Crystal Dragon, Adult", 13}, {"Drake, Magma", 13}, {"Drake, Rage, Fiendish", 13},
		{"Ethereal Dragon, Mature Adult", 13}, {"Golden Protector", 13}, {"Green Dragon, Adult", 13},
		{"Howling Dragon, Young Adult", 13}, {"Oceanus Dragon, Adult", 13}, {"Pyroclastic Dragon, Adult", 13},
		{"Radiant Dragon, Young Adult", 13}, {"Red Dragon, Young Adult", 13}, {"Rust Dragon, Adult", 13},
		{"Shadow Dragon, Adult", 13}, {"Silver Dragon, Young Adult", 13}, {"Spinewyrm, Mature Adult", 13},
		{"Steel Dragon, Very Old", 13}, {"Tarterian Dragon, Young Adult", 13}, {"Tome Dragon, Young Adult", 13},
		{"Topaz Dragon, Young Adult", 13}, {"Battle Dragon, Mature Adult", 14}, {"Black Dragon, Mature Adult", 14},
		{"Blue Dragon, Adult", 14}, {"Brainstealer Dragon, Adult", 14}, {"Chole Dragon, Adult", 14},
		{"Copper Dragon, Adult", 14}, {"Elysian Dragon, Mature Adult", 14}, {"Gloom Dragon, Mature Adult", 14},
		{"Gold Dragon, Young Adult", 14}, {"Howling Dragon, Adult", 14}, {"Landwyrm, Tundra", 14},
		{"Lantern Sea Serpent, Mature Adult", 14}, {"Radiant Dragon, Adult", 14}, {"Sand Dragon, Mature Adult", 14},
		{"Sapphire Dragon, Adult", 14}, {"Spiked Sea Serpent, Mature Adult", 14}, {"Styx Dragon, Mature Adult", 14},
		{"Sunwyrm", 14}, {"Tarterian Dragon, Adult", 14}, {"Adamantine Dragon, Young Adult", 15},
		{"Amethyst Dragon, Adult", 15}, {"Astral Dragon, Mature Adult", 15}, {"Beast Dragon, Adult", 15},
		{"Brass Dragon, Mature Adult", 15}, {"Bronze Dragon, Adult", 15}, {"Chaos Dragon, Mature Adult", 15},
		{"Concordant Dragon, Adult", 15}, {"Crested Sea Serpent, Old", 15}, {"Drake, Sea", 15},
		{"Emerald Dragon, Adult", 15}, {"Ethereal Dragon, Old", 15}, {"Fang Dragon, Old", 15},
		{"Grayhawk Dragon, Mature Adult", 15}, {"Hex Dragon, Mature Adult", 15}, {"Mercury Dragon, Old", 15},
		{"Mist Dragon, Old", 15}, {"Red Dragon, Adult", 15}, {"Rust Dragon, Mature Adult", 15},
		{"Silver Dragon, Adult", 15}, {"Spinewyrm, Old", 15}, {"Steel Dragon, Ancient", 15},
		{"Topaz Dragon, Adult", 15}, {"White Dragon, Old", 15}, {"Adamantine Dragon, Adult", 16},
		{"Arboreal Dragon, Mature Adult", 16}, {"Beast Dragon, Mature Adult", 16}, {"Black Dragon, Old", 16},
		{"Blue Dragon, Mature Adult", 16}, {"Brainstealer Dragon, Mature Adult", 16}, {"Chaos Dragon, Old", 16},
		{"Chole Dragon, Mature Adult", 16}, {"Copper Dragon, Mature Adult", 16}, {"Crystal Dragon, Mature Adult", 16},
		{"Elysian Dragon, Old", 16}, {"Ethereal Dragon, Very Old", 16}, {"Gloom Dragon, Old", 16},
		{"Gold Dragon, Adult", 16}, {"Green Dragon, Mature Adult", 16}, {"Landwyrm, Jungle", 16},
		{"Lantern Sea Serpent, Old", 16}, {"Oceanus Dragon, Mature Adult", 16}, {"Pyroclastic Dragon, Mature Adult", 16},
		{"Rust Dragon, Old", 16}, {"Sand Dragon, Old", 16}, {"Sapphire Dragon, Mature Adult", 16},
		{"Shadow Dragon, Mature Adult", 16}, {"Spiked Sea Serpent, Old", 16}, {"Steel Dragon, Wyrm", 16},
		{"Tome Dragon, Adult", 16}, {"Amethyst Dragon, Mature Adult", 17}, {"Astral Dragon, Old", 17},
		{"Axial Dragon, Adult", 17}, {"Battle Dragon, Old", 17}, {"Brainstealer Dragon, Old", 17},
		{"Brass Dragon, Old", 17}, {"Bronze Dragon, Mature Adult", 17}, {"Chaos Dragon, Very Old", 17},
		{"Concordant Dragon, Mature Adult", 17}, {"Drake, Storm", 17}, {"Emerald Dragon, Mature Adult", 17},
		{"Ethereal Dragon, Ancient", 17}, {"Fang Dragon, Very Old", 17}, {"Grayhawk Dragon, Old", 17},
		{"Hex Dragon, Old", 17}, {"Howling Dragon, Mature Adult", 17}, {"Mercury Dragon, Very Old", 17},
		{"Mist Dragon, Very Old", 17}, {"Radiant Dragon, Mature Adult", 17}, {"Rust Dragon, Very Old", 17},
		{"Spinewyrm, Very Old", 17}, {"Styx Dragon, Old", 17}, {"Tarterian Dragon, Mature Adult", 17},
		{"Tome Dragon, Mature Adult", 17}, {"White Dragon, Very Old", 17}, {"Arboreal Dragon, Old", 18},
		{"Battle Dragon, Very Old", 18}, {"Beast Dragon, Old", 18}, {"Black Dragon, Very Old", 18},
		{"Blue Dragon, Old", 18}, {"Chole Dragon, Old", 18}, {"Crested Sea Serpent, Very Old", 18},
		{"Crystal Dragon, Old", 18}, {"Elysian Dragon, Very Old", 18}, {"Ethereal Dragon, Wyrm", 18},
		{"Fang Dragon, Ancient", 18}, {"Gloom Dragon, Very Old", 18}, {"Green Dragon, Old", 18},
		{"Landwyrm, Desert", 18}, {"Mercury Dragon, Ancient", 18}, {"Mist Dragon, Ancient", 18},
		{"Oceanus Dragon, Old", 18}, {"Pyroclastic Dragon, Old", 18}, {"Red Dragon, Mature Adult", 18},
		{"Sand Dragon, Very Old", 18}, {"Shadow Dragon, Old", 18}, {"Silver Dragon, Mature Adult", 18},
		{"Spiked Sea Serpent, Very Old", 18}, {"Steel Dragon, Great Wyrm", 18}, {"Styx Dragon, Very Old", 18},
		{"Topaz Dragon, Mature Adult", 18}, {"White Dragon, Ancient", 18}, {"Adamantine Dragon, Mature Adult", 19},
		{"Amethyst Dragon, Old", 19}, {"Arboreal Dragon, Very Old", 19}, {"Astral Dragon, Very Old", 19},
		{"Axial Dragon, Mature Adult", 19}, {"Battle Dragon, Ancient", 19}, {"Beast Dragon, Very Old", 19},
		{"Black Dragon, Ancient", 19}, {"Blue Dragon, Very Old", 19}, {"Brass Dragon, Very Old", 19},
		{"Bronze Dragon, Old", 19}, {"Chaos Dragon, Ancient", 19}, {"Concordant Dragon, Old", 19},
		{"Copper Dragon, Old", 19}, {"Crystal Dragon, Very Old", 19}, {"Elysian Dragon, Ancient", 19},
		{"Emerald Dragon, Old", 19}, {"Ethereal Dragon, Great Wyrm", 19}, {"Fang Dragon, Wyrm", 19},
		{"Gloom Dragon, Ancient", 19}, {"Gold Dragon, Mature Adult", 19}, {"Grayhawk Dragon, Very Old", 19},
		{"Green Dragon, Very Old", 19}, {"Hex Dragon, Very Old", 19}, {"Howling Dragon, Old", 19},
		{"Lantern Sea Serpent, Very Old", 19}, {"Mercury Dragon, Wyrm", 19}, {"Mist Dragon, Wyrm", 19},
		{"Oceanus Dragon, Very Old", 19}, {"Pyroclastic Dragon, Very Old", 19}, {"Radiant Dragon, Old", 19},
		{"Rust Dragon, Ancient", 19}, {"Sapphire Dragon, Old", 19}, {"Shadow Dragon, Very Old", 19},
		{"Spinewyrm, Ancient", 19}, {"Styx Dragon, Ancient", 19}, {"Tarterian Dragon, Old", 19},
		{"White Dragon, Wyrm", 19}, {"Adamantine Dragon, Old", 20}, {"Amethyst Dragon, Very Old", 20},
		{"Arboreal Dragon, Ancient", 20}, {"Battle Dragon, Wyrm", 20}, {"Beast Dragon, Ancient", 20},
		{"Black Dragon, Wyrm", 20}, {"Brainstealer Dragon, Very Old", 20}, {"Brass Dragon, Ancient", 20},
		{"Bronze Dragon, Very Old", 20}, {"Chaos Dragon, Wyrm", 20}, {"Chole Dragon, Very Old", 20},
		{"Copper Dragon, Very Old", 20}, {"Crested Sea Serpent, Ancient", 20}, {"Drake, Fire", 20},
		{"Elysian Dragon, Wyrm", 20}, {"Emerald Dragon, Very Old", 20}, {"Gloom Dragon, Wyrm", 20},
		{"Grayhawk Dragon, Ancient", 20}, {"Hex Dragon, Ancient", 20}, {"Howling Dragon, Very Old", 20},
		{"Landwyrm, Swamp", 20}, {"Linnorm, Gray", 20}, {"Oceanus Dragon, Ancient", 20},
		{"Pyroclastic Dragon, Ancient", 20}, {"Radiant Dragon, Very Old", 20}, {"Red Dragon, Old", 20},
		{"Rust Dragon, Wyrm", 20}, {"Sapphire Dragon, Very Old", 20}, {"Silver Dragon, Old", 20},
		{"Spiked Sea Serpent, Ancient", 20}, {"Spinewyrm, Wyrm", 20}, {"Ssvaklor, Greater", 20},
		{"Styx Dragon, Wyrm", 20}, {"Tarterian Dragon, Very Old", 20}, {"Tome Dragon, Old", 20},
		{"Topaz Dragon, Old", 20}, {"Wormdrake", 20}, {"Adamantine Dragon, Very Old", 21},
		{"Arboreal Dragon, Wyrm", 21}, {"Astral Dragon, Ancient", 21}, {"Axial Dragon, Old", 21},
		{"Blue Dragon, Ancient", 21}, {"Brainstealer Dragon, Ancient", 21}, {"Brass Dragon, Wyrm", 21},
		{"Chole Dragon, Ancient", 21}, {"Concordant Dragon, Very Old", 21}, {"Crystal Dragon, Ancient", 21},
		{"Fang Dragon, Great Wyrm", 21}, {"Gold Dragon, Old", 21}, {"Grayhawk Dragon, Wyrm", 21},
		{"Green Dragon, Ancient", 21}, {"Hex Dragon, Wyrm", 21}, {"Howling Dragon, Ancient", 21},
		{"Lantern Sea Serpent, Ancient", 21}, {"Mercury Dragon, Great Wyrm", 21}, {"Mist Dragon, Great Wyrm", 21},
		{"Oceanus Dragon, Wyrm", 21}, {"Pyroclastic Dragon, Wyrm", 21}, {"Radiant Dragon, Ancient", 21},
		{"Red Dragon, Very Old", 21}, {"Sand Dragon, Ancient", 21}, {"Shadow Dragon, Ancient", 21},
		{"Silver Dragon, Very Old", 21}, {"Spiked Sea Serpent, Wyrm", 21}, {"Tarterian Dragon, Ancient", 21},
		{"Topaz Dragon, Very Old", 21}, {"White Dragon, Great Wyrm", 21}, {"Adamantine Dragon, Ancient", 22},
		{"Amethyst Dragon, Ancient", 22}, {"Arboreal Dragon, Great Wyrm", 22}, {"Axial Dragon, Very Old", 22},
		{"Battle Dragon, Great Wyrm", 22}, {"Beast Dragon, Wyrm", 22}, {"Black Dragon, Great Wyrm", 22},
		{"Bronze Dragon, Ancient", 22}, {"Chaos Dragon, Great Wyrm", 22}, {"Concordant Dragon, Ancient", 22},
		{"Copper Dragon, Ancient", 22}, {"Crested Sea Serpent, Wyrm", 22}, {"Crystal Dragon, Wyrm", 22},
		{"Elysian Dragon, Great Wyrm", 22}, {"Emerald Dragon, Ancient", 22}, {"Gloom Dragon, Great Wyrm", 22},
		{"Gold Dragon, Very Old", 22}, {"Green Dragon, Wyrm", 22}, {"Howling Dragon, Wyrm", 22},
		{"Landwyrm, Mountain", 22}, {"Oceanus Dragon, Great Wyrm", 22}, {"Pyroclastic Dragon, Great Wyrm", 22},
		{"Radiant Dragon, Wyrm", 22}, {"Rust Dragon, Great Wyrm", 22}, {"Sapphire Dragon, Ancient", 22},
		{"Shadow Dragon, Wyrm", 22}, {"Spinewyrm, Great Wyrm", 22}, {"Styx Dragon, Great Wyrm", 22},
		{"Tarterian Dragon, Wyrm", 22}, {"Tome Dragon, Very Old", 22}, {"Adamantine Dragon, Wyrm", 23},
		{"Astral Dragon, Wyrm", 23}, {"Axial Dragon, Ancient", 23}, {"Beast Dragon, Great Wyrm", 23},
		{"Blue Dragon, Wyrm", 23}, {"Brainstealer Dragon, Wyrm", 23}, {"Brass Dragon, Great Wyrm", 23},
		{"Bronze Dragon, Wyrm", 23}, {"Chole Dragon, Wyrm", 23}, {"Concordant Dragon, Wyrm", 23},
		{"Copper Dragon, Wyrm", 23}, {"Grayhawk Dragon, Great Wyrm", 23}, {"Howling Dragon, Great Wyrm", 23},
		{"Lantern Sea Serpent, Wyrm", 23}, {"Radiant Dragon, Great Wyrm", 23}, {"Red Dragon, Ancient", 23},
		{"Sapphire Dragon, Wyrm", 23}, {"Silver Dragon, Ancient", 23}, {"Spiked Sea Serpent, Great Wyrm", 23},
		{"Tarterian Dragon, Great Wyrm", 23}, {"Tome Dragon, Ancient", 23}, {"Topaz Dragon, Ancient", 23},
		{"Adamantine Dragon, Great Wyrm", 24}, {"Amethyst Dragon, Wyrm", 24}, {"Astral Dragon, Great Wyrm", 24},
		{"Concordant Dragon, Great Wyrm", 24}, {"Crested Sea Serpent, Great Wyrm", 24}, {"Crystal Dragon, Great Wyrm", 24},
		{"Emerald Dragon, Wyrm", 24}, {"Gold Dragon, Ancient", 24}, {"Green Dragon, Great Wyrm", 24},
		{"Hex Dragon, Great Wyrm", 24}, {"Red Dragon, Wyrm", 24}, {"Sand Dragon, Wyrm", 24},
		{"Shadow Dragon, Great Wyrm", 24}, {"Silver Dragon, Wyrm", 24}, {"Topaz Dragon, Wyrm", 24},
		{"Axial Dragon, Wyrm", 25}, {"Blue Dragon, Great Wyrm", 25}, {"Brainstealer Dragon, Great Wyrm", 25},
		{"Bronze Dragon, Great Wyrm", 25}, {"Chole Dragon, Great Wyrm", 25}, {"Copper Dragon, Great Wyrm", 25},
		{"Emerald Dragon, Great Wyrm", 25}, {"Gold Dragon, Wyrm", 25}, {"Lantern Sea Serpent, Great Wyrm", 25},
		{"Linnorm, Dread", 25}, {"Sapphire Dragon, Great Wyrm", 25}, {"Tome Dragon, Wyrm", 25},
		{"Amethyst Dragon, Great Wyrm", 26}, {"Hellfire Wyrm", 26}, {"Red Dragon, Great Wyrm", 26},
		{"Silver Dragon, Great Wyrm", 26}, {"Tome Dragon, Great Wyrm", 26}, {"Topaz Dragon, Great Wyrm", 26},
		{"Axial Dragon, Great Wyrm", 27}, {"Gold Dragon, Great Wyrm", 27}, {"Sand Dragon, Great Wyrm", 27},
		{"Linnorm, Corpse Tearer", 28},
	},
	"Elemental": {
		{"Rainrunner", 0}, {"Earthdelver", 0}, {"Firesnake", 0}, {"Windraptor", 0}, {"Air Elemental, Small", 1},
		{"Cinderbrute", 1}, {"Cloudscout", 1}, {"Earth Elemental, Small", 1}, {"Fire Elemental, Small", 1},
		{"Ice Para-Elemental, Small", 1}, {"Magma Para-Elemental, Small", 1}, {"Ooze Para-Elemental, Small", 1},
		{"Sandknight", 1}, {"Smoke Para-Elemental, Small", 1}, {"Squid, Air Element", 1}, {"Water Elemental, Small", 1},
		{"Wave Archer", 1}, {"Grue, Air-Ildriss", 2}, {"Grue, Earth-Chaggrin", 2}, {"Grue, Fire-Harginn", 2},
		{"Grue, Mud", 2}, {"Grue, Water-Vardigg", 2}, {"Leopard, Wood Element", 2}, {"Stone Spike", 2},
		{"Storm Elemental, Small", 2}, {"Thoqqua", 2}, {"Air Elemental, Med", 3}, {"Ape, Fire Element", 3},
		{"Darkness, Pseudo-Elemental, Small", 3}, {"Dust Twister", 3}, {"Earth Elemental, Med", 3}, {"Fire Bat", 3},
		{"Fire Elemental, Med", 3}, {"Ice Para-Elemental, Med", 3}, {"Magma Para-Elemental, Med", 3}, {"Magmin", 3},
		{"Ooze Para-Elemental, Med", 3}, {"Smoke Para-Elemental, Med", 3}, {"Water Elemental, Med", 3},
		{"Air Elementite Swarm", 4}, {"Earth Elementite Swarm", 4}, {"Fire Elementite Swarm", 4}, {"Storm Elemental, Med", 4},
		{"Tiger, Water Element", 4}, {"Water Elementite Swarm", 4}, {"Wind Warrior", 4}, {"Air Elemental, Large", 5},
		{"Darkness, Pseudo-Elemental, Medium", 5}, {"Earth Elemental, Large", 5}, {"Earth Whisper", 5},
		{"Fire Elemental, Large", 5}, {"Ice Para-Elemental, Large", 5}, {"Magma Para-Elemental, Large", 5},
		{"Ooze Para-Elemental, Large", 5}, {"Smoke Para-Elemental, Large", 5}, {"Water Elemental, Large", 5},
		{"Belker", 6}, {"Chraal", 6}, {"Rhinoceros, Earth Element", 6}, {"Storm Elemental, Large", 6},
		{"Air Elemental, Huge", 7}, {"Breathdrinker", 7}, {"Darkness, Pseudo-Elemental, Large", 7}, {"Earth Elemental, Huge", 7},
		{"Fire Elemental, Huge", 7}, {"Ice Para-Elemental, Huge", 7}, {"Invisible Stalker", 7}, {"Magma Para-Elemental, Huge", 7},
		{"Ooze Para-Elemental, Huge", 7}, {"Smoke Para-Elemental, Huge", 7}, {"Water Elemental, Huge", 7},
		{"Inferno Spider", 8}, {"Shambling Mound, Cold Element", 8}, {"Storm Elemental, Huge", 8}, {"Air Elemental, Greater", 9},
		{"Caller from the Deeps", 9}, {"Earth Elemental, Greater", 9}, {"Fire Elemental, Greater", 9}, {"Galeb Duhr", 9},
		{"Ice Para-Elemental, Greater", 9}, {"Immoth", 9}, {"Magma Para-Elemental, Greater", 9}, {"Ooze Para-Elemental, Greater", 9},
		{"Smoke Para-Elemental, Greater", 9}, {"Water Elemental, Greater", 9}, {"Sickstone Elemental", 10},
		{"Storm Elemental, Greater", 10}, {"Air Elemental, Elder", 11}, {"Earth Elemental, Elder", 11},
		{"Fire Elemental, Elder", 11}, {"Ice Para-Elemental, Elder", 11}, {"Magma Para-Elemental, Elder", 11},
		{"Ooze Para-Elemental, Elder", 11}, {"Smoke Para-Elemental, Elder", 11}, {"Water Elemental, Elder", 11},
		{"Storm Elemental, Elder", 12}, {"Weird, Air", 12}, {"Weird, Earth", 12}, {"Weird, Fire", 12},
		{"Weird, Water", 12}, {"Cinder Swarm", 13}, {"Living Holocaust", 13}, {"Cyclonic Ravager", 15},
		{"Holocaust Disciple", 15}, {"Omnimental", 15}, {"Waterveilded Assassin", 15}, {"Weird, Ice", 15},
		{"Weird, Snow", 15}, {"Tempest", 16}, {"Air Monolith", 17}, {"Earth Monolith", 17},
		{"Fire Monolith", 17}, {"Water Monolith", 17}, {"Black Rock Triskelion", 18},
	},
	"Fey": {
		{"Feytouched", 0}, {"Jermlaine", 0}, {"Uldra", 0}, {"Domovoi", 1}, {"Grig", 1}, {"House Brownie", 1},
		{"Nixie", 1}, {"Petal", 1}, {"Rusalka", 1}, {"Shadar-Kai", 1}, {"Chaneque", 2}, {"Redcap, 5HD", 2},
		{"Satyr", 2}, {"Splinterwaif", 2}, {"Wolf, Spirit", 2}, {"Dryad", 3}, {"Redcap, 6HD", 3},
		{"Satyr, Anarchic", 3}, {"Spriggan-Enlarged Form", 3}, {"Spriggan-Natural Form", 3}, {"Vodyanoi", 3},
		{"Half-Fey Centaur", 4}, {"Nereid", 4}, {"Pixie", 4}, {"Redcap, 8HD", 4}, {"Satyr with Pipes", 4},
		{"Thorn", 4}, {"Yuki-On-Na", 4}, {"Fossergrim", 5}, {"Joystealer", 5}, {"Pixie with Otto's Irresistible Dance", 5},
		{"Sirine", 5}, {"Winterling", 5}, {"Glaistig", 6}, {"Redcap, 10HD", 6}, {"Splinterwaif Knave", 6},
		{"Wendigo", 6}, {"Gloura", 7}, {"Lunar Ravager", 7}, {"Mirage Mullah", 7}, {"Nymph", 7}, {"Oread", 7},
		{"Redcap, 12HD", 7}, {"Glaistig Mindbender", 8}, {"Redcap, 14HD", 8}, {"Shimmerling Swarm", 8},
		{"Rimefire Eidolon", 9}, {"Kelpie", 10}, {"Redcap, 16HD", 10}, {"Redcap, 18HD", 11}, {"Verdant Prince", 11},
		{"Redcap, 20HD", 12}, {"Ragewalker", 14}, {"Ocean Strider", 18}, {"Wild Watcher", 19}, {"Spirit of the Land", 23},
	},
	"Giant": {
		{"Merrow", 3}, {"Ogre", 3}, {"Troll, Forest", 3}, {"Fensir", 5}, {"Ogre, Skullcrusher", 5},
		{"Scrag", 5}, {"Troll", 5}, {"Ettin", 6}, {"Giant, Bog", 6}, {"Ogre Guard Thrall", 6},
		{"Ettin, Fire-Souled", 7}, {"Ettin, Hooded Pupil", 7}, {"Hill Giant", 7}, {"Ogre, Barbarian 4th", 7},
		{"Troll, Crystalline", 7}, {"Troll, Wasteland", 7}, {"Fensir, Rakka", 8}, {"Giant, Stone", 8},
		{"Ogre Mage", 8}, {"Ogre, Skullcrusher, Fighter 3rd", 8}, {"Troll, Cave", 8}, {"Xilob", 8},
		{"Giant, Frost", 9}, {"Giant, Stone Elder", 9}, {"Half-Troll Barbazu", 9}, {"Giant, Craa'ghoran", 10},
		{"Giant, Fire", 10}, {"Giant, Frost Spiritspeaker", 10}, {"Giant, Frost Tundra Scout", 10}, {"Giant, Sand", 10},
		{"Troll, Mountain", 10}, {"Formorian", 11}, {"Giant, Cloud", 11}, {"Giant, Fire, Dragonic", 11},
		{"Giant, Forest", 11}, {"Giant, Frost, Barbarian 2nd", 11}, {"Giant, Hill, Dire Wereboar", 11},
		{"Maur", 11}, {"Troll Hunter", 11}, {"Firbolg", 12}, {"Giant, Sun", 12}, {"Giant, Storm", 13},
		{"Giant, Eldritch", 15}, {"Giant, Sand, Fighter 5th", 15}, {"Giant, Death", 16}, {"Giant Frost, Jarl", 17},
		{"Raam", 17}, {"Giant, Shadow", 18}, {"Geriviar", 19}, {"Giant, Ocean", 19}, {"Giant, Eldritch, Cleric 11th", 20},
		{"Giant, Mountain", 26},
	},
	"Humanoid": {
		{"Kobold", 0}, {"Goblin", 0}, {"Xvart", 0}, {"Asherati", 0}, {"Aventi", 0}, {"Bhuka", 0}, {"Changeling", 0},
		{"Darfellan", 1}, {"Dwarf, Deep", 1}, {"Dwarf, Hill", 1}, {"Dwarf, Mountain", 1}, {"Elf, Aquatic", 1},
		{"Elf, Grey", 1}, {"Elf, Half", 1}, {"Elf, High", 1}, {"Elf, Wild", 1}, {"Elf, Wood", 1}, {"Gnome, Forest", 1},
		{"Gnome, Rock", 1}, {"Goblin, Forestkith", 1}, {"Goblin, Snow", 1}, {"Grippli", 1}, {"Hadozee", 1},
		{"Halfling, Deep", 1}, {"Halfling, Lightfoot", 1}, {"Halfling, Tallfellow", 1}, {"Half-Orc", 1},
		{"Hobgoblin", 1}, {"Kenku", 1}, {"Locathah", 2}, {"Merfolk", 1}, {"Neanderthal", 1}, {"Norker", 1},
		{"Orc", 1}, {"Phanaton", 1}, {"Shifter", 1}, {"Tortle", 1}, {"Drow", 1}, {"Duergar", 1}, {"Dwarf, Frost", 1},
		{"Dwarf, Glacier", 1}, {"Gith", 1}, {"Githyanki", 1}, {"Githzerai", 1}, {"Gnoll", 1}, {"Gnome, Fire", 1},
		{"Lizardfolk", 1}, {"Quinametin", 1}, {"Selkie", 1}, {"Svirfneblin", 1}, {"Troglodyte", 1}, {"Varag", 1},
		{"Belgoi", 2}, {"Bugbear", 2}, {"Crucian", 2}, {"Flind", 2}, {"Human, Wererat", 2}, {"Orc, Snow Shaman", 2},
		{"Phaerlock", 2}, {"Bugbear, Chameleon", 3}, {"Dark Creeper", 3}, {"Human, Werewolf", 3}, {"Dark Stalker", 4},
		{"Human, Wereboar", 4}, {"Werecrocodile Human", 4}, {"Fighter, Scorned", 5}, {"Human, Werebear", 5},
		{"Human, Weretiger", 5}, {"Inspired", 5}, {"Half-Janni", 6}, {"Drow, Loth-Touched", 7}, {"Barbarian, Scorned", 9},
		{"Human, Woodling Druid", 11}, {"Human, Werewolf Lord", 14},
	},
	"Magical Beast": {
		{"Elysian Thrush", 0}, {"Moonrat", 0}, {"Monkey, Flying", 0}, {"Blood Hawk", 0}, {"Corollax", 0},
		{"Dire Rat, Fiendish", 0}, {"Floater", 0}, {"Skiurid", 0}, {"Stirge", 0}, {"Abrian", 1}, {"Ash Rat", 1},
		{"Darkmantle", 1}, {"Elven Hound", 1}, {"Flame Snake, Minor", 1}, {"Krenshar", 1}, {"Shadow Asp", 1},
		{"ur' Epona", 1}, {"Zhackal", 1}, {"Ashworm", 2}, {"Blink Dog", 2}, {"Bloodsilk Spider", 2},
		{"Branta", 2}, {"Cloaked Ape", 2}, {"Cranium Rat Swarm, Lesser Pack", 2}, {"Death Dog", 2},
		{"Giant Scarab Beetle", 2}, {"Greenspawn Leaper", 2}, {"Grimalkin", 2}, {"Hippocampus", 2},
		{"Hippogriff", 2}, {"Jackalwere", 2}, {"Phase Wasp", 2}, {"Raven, Giant", 2}, {"Shocker Lizard", 2},
		{"Terlen", 2}, {"Thrum Worm", 2}, {"Tomb Spider Broodswarm", 2}, {"Worg", 2}, {"Yeshir", 2},
		{"Ankheg", 3}, {"Camelopardel", 3}, {"Cockatrice", 3}, {"Cranial Encyster", 3}, {"Eagle, Giant", 3},
		{"Ethereal Marauder", 3}, {"Guardian Steed", 3}, {"Ice Toad", 3}, {"Owl, Giant", 3}, {"Pegasus", 3},
		{"Phoera", 3}, {"Rasclinn", 3}, {"Sand Hunter", 3}, {"Seawolf", 3}, {"Senmury", 3}, {"Stone Flyer", 3},
		{"Unicorn", 3}, {"Vazalka", 3}, {"Vulture, Giant", 3}, {"Apocalypse Frog Swarm", 4}, {"Aranea", 4},
		{"Asperi", 4}, {"Bluespawn Ambusher", 4}, {"Chekryan", 4}, {"Deep Hound", 4}, {"Displacer Beast", 4},
		{"Fordorran", 4}, {"Griffon", 4}, {"Hammerclaw", 4}, {"Hydra, 5 Headed", 4}, {"Lion, Celestial", 4},
		{"Lirr", 4}, {"Owlbear", 4}, {"Sea Cat", 4}, {"War Turtle", 4}, {"Wight, Shadow", 4},
		{"Avalancher", 5}, {"Basilisk", 5}, {"Beacon Moth", 5}, {"Cranium Rat Swarm, Average Pack", 5},
		{"Dune Reaper, Drone", 5}, {"Elder Serpent Huge Viper", 5}, {"Feral Yowler", 5}, {"Gambol", 5},
		{"Hetfish", 5}, {"Hydra, 6 Headed", 5}, {"Manticore", 5}, {"Phase Spider", 5}, {"Sphinx, Canisphinx", 5},
		{"Sphinx, Hieracosphinx", 5}, {"Sphinx, Saurophinx", 5}, {"Spider Eater", 5}, {"Ti-Khana Deinonychus", 5},
		{"Urskan", 5}, {"White Hart", 5}, {"Winter Wolf", 5}, {"Blood Ape", 6}, {"Bluespawn Stormlizard", 6},
		{"Digester", 6}, {"Girallon", 6}, {"Hydra, 5 Headed Cryo", 6}, {"Hydra, 5 Headed Pyro", 6},
		{"Hydra, 7 Headed", 6}, {"Lamia", 6}, {"Lith", 6}, {"Prismfly Swarm", 6}, {"Quanlos", 6},
		{"Redspawn Firebelcher", 6}, {"Sand Howler", 6}, {"Shark, Huge Fiendish", 6}, {"Tomb Spider", 6},
		{"Whitespawn Iceskidder", 6}, {"Zezir", 6}, {"Bearhound", 7}, {"Bulette", 7}, {"Chimera", 7},
		{"Dragonne", 7}, {"Dragonne, Axiomatic", 7}, {"Elsewhale", 7}, {"Flame Snake, Lesser", 7},
		{"Frost Salamander", 7}, {"Greenspawn Razorfiend", 7}, {"Hydra, 6 Headed Cryo", 7}, {"Hydra, 6 Headed Pyro", 7},
		{"Hydra, 8 Headed", 7}, {"Leskylor", 7}, {"Mudmaw", 7}, {"Ramfish", 7}, {"Remorhaz", 7},
		{"Simurgh", 7}, {"Sphinx, Criosphinx", 7}, {"Swamplight Lynx", 7}, {"Tyrg", 7}, {"Behir", 8},
		{"Carcass Crab", 8}, {"Gorgon", 8}, {"Gravorg", 8}, {"Gray Render", 8}, {"Hellwasp Swarm", 8},
		{"Hydra, 7 Headed Cryo", 8}, {"Hydra, 7 Headed Pyro", 8}, {"Hydra, 9 Headed", 8}, {"Kamadan", 8},
		{"Kaortic Hulk", 8}, {"Kuldurath", 8}, {"Lammasu", 8}, {"Limbo Stalker", 8}, {"Nethersight Mastiff", 8},
		{"Pack Fiend", 8}, {"Sisiutl", 8}, {"Sphinx, Gynosphinx", 8}, {"Sphinx, Threskiphinx", 8},
		{"Ankheg, Chimeric", 9}, {"Blackspawn Stalker", 9}, {"Bluespawn Burrower", 9}, {"Bulette, Axiomatic", 9},
		{"Dune Reaper, Warrior", 9}, {"Gray Shiver", 9}, {"Hydra, 8 Headed Cryo", 9}, {"Hydra, 8 Headed Pyro", 9},
		{"Hydra, 10 Headed", 9}, {"Ironclad Mauler", 9}, {"Sphinx, Androsphinx", 9}, {"Yrthak", 9},
		{"Dunewinder", 10}, {"Gaspar", 10}, {"Gathra", 10}, {"Hydra, 9 Headed Cryo", 10}, {"Hydra, 9 Headed Pyro", 10},
		{"Hydra, 11 Headed", 10}, {"Leskylor, Three Headed", 10}, {"Mooncalf", 10}, {"Razor Boar", 10},
		{"Shedu", 10}, {"Vartangoin, Rager", 10}, {"Cranium Rat Swarm, Greater Pack", 11}, {"Hydra, 10 Headed Cryo", 11},
		{"Hydra, 10 Headed Pyro", 11}, {"Hydra, 12 Headed", 11}, {"Mivilorn", 11}, {"Redspawn Birther", 11},
		{"Roc, Fiendish", 11}, {"Sandworm", 11}, {"Spirit of the Air", 11}, {"Tlalusk", 11}, {"Varrangoin, Arcanist", 11},
		{"Brood Keeper Larva Swarm", 12}, {"Displacer Beast Pack Lord", 12}, {"Frost Worm", 12}, {"Hydra, 11 Headed Cryo", 12},
		{"Hydra, 11 Headed Pyro", 12}, {"Kraken", 12}, {"Purple Worm", 12}, {"Rampager", 12}, {"Roper", 12},
		{"Shadow Spider", 12}, {"Spellgaunt", 12}, {"Sphinx, Crocophinx", 12}, {"Thunderbird", 12},
		{"Celestial Charger", 13}, {"Hydra, 12 Headed Cryo", 13}, {"Hydra, 12 Headed Pyro", 13},
		{"Maurid Advanced Chimera", 15}, {"Nightmare Beast", 15}, {"Overworm", 15}, {"Brood Keeper", 16},
		{"Cloud Ray", 16}, {"Flame Snake, Greater", 16}, {"Mivilorn, Elite Demon", 16}, {"Mooncalf, Advanced", 16},
		{"Disenchanter", 17}, {"Lucent Worm", 17}, {"Nightmare Beast, Advanced Elite", 18}, {"Chronotryn", 19},
		{"Cipactli", 20}, {"Deathraven Swarm", 20}, {"Tarrasque", 20}, {"Thunder Worm", 21}, {"Roc, Chaos", 22},
		{"Phoenix", 24}, {"Leviathan", 25}, {"Fiendwurm", 28},
	},
	"Monstrous Humanoid": {
		{"Grimlock", 1}, {"Lizardfolk, Poison Dusk", 1}, {"Thri-Keen", 1}, {"Whitespawn Hordeling", 1}, {"Yurian", 1},
		{"Abeil, Vassal", 2}, {"Goatfolk", 2}, {"Goblyn", 2}, {"Greenspawn Sneak", 2}, {"Grimlock, Voidmind", 2},
		{"Kuo-Toa", 2}, {"Loxo", 2}, {"Malenti", 2}, {"Nycter", 2}, {"Ophidian", 2}, {"Sahuagin", 2},
		{"Armand", 3}, {"Blindheim", 3}, {"Bluespawn Stoneglider", 3}, {"Boggle", 3}, {"Centaur", 3},
		{"Chupacabra", 3}, {"Derro", 3}, {"Doppelganger", 3}, {"Dragonkin", 3}, {"Khaasta", 3},
		{"Lizardfolk, Blackscale", 3}, {"Xtabay", 3}, {"Yeti", 3}, {"Yuan-Ti Pureblood", 3}, {"Blackspawn Raider", 4},
		{"Gargoyle", 4}, {"Hag, Dune", 4}, {"Hag, Dusk", 4}, {"Harpy", 4}, {"Harssaf", 4}, {"Kapocinth", 4},
		{"Lhosk", 4}, {"Marruspawn, Marrulurk", 4}, {"Minotaur", 4}, {"Nagatha", 4}, {"Rhek", 4},
		{"Sea Hag", 4}, {"Whitespawn Hunter", 4}, {"Witchknife", 4}, {"Yak Folk", 4}, {"Zern Blade Thrall", 4},
		{"Green Hag", 5}, {"Marruspawn, Marrusult", 5}, {"Marruspawn, Marrutact", 5}, {"Minotaur, Faerzress-Infused", 5},
		{"Tauric Hobgoblin/Griffon", 5}, {"Yuan-Ti Halfblood", 5}, {"Abeil, Soldier", 6}, {"Annis", 6}, {"Kopru", 6},
		{"Marzanna", 6}, {"Nuckalavee", 6}, {"Ormyrr", 6}, {"Phoelarch", 6}, {"Redspawn Arcaniss", 6},
		{"Vazalkyon", 6}, {"Zern", 6}, {"Medusa", 7}, {"Minotaur, Greathorn", 7}, {"Orangeseer", 7},
		{"Scorpionfolk", 7}, {"Yeti, Abominable", 7}, {"Yuan-Ti Abomination", 7}, {"Yuan-Ti Ignan", 7},
		{"Jackal Lord", 8}, {"Braxat", 9}, {"Desmodu", 9}, {"Doppelganger, Greater", 9}, {"Gulgar", 9},
		{"Bluespawn Godslayer", 10}, {"Spell Weaver", 10}, {"Nagpa", 11}, {"Skindancer", 11}, {"Abeil, Queen", 12},
		{"Protean Scourge", 12}, {"Troll, War", 12}, {"Sarkrith, Spelleater", 13}, {"Doppelganger, Ethereal", 15},
		{"Kuo-Toa Leviathan", 15}, {"Vermin Lord", 17},
	},
	"Ooze": {
		{"Bloodbloater", 1}, {"Living Spell, Burning Hands", 1}, {"Flotsam Ooze", 2}, {"Living Spell, Color Spray", 2},
		{"Living Spell, Sickening Sleep", 2}, {"Amoebic Crawler", 3}, {"Gelatinous Cube", 3}, {"Living Spell, Flaming Sphere", 3},
		{"Slime Creature, Small", 3}, {"Gray Ooze", 4}, {"Living Spell, Fireball", 4}, {"Olive Slime", 4},
		{"Summoning Ooze", 4}, {"Ochre Jelly", 5}, {"Ooze, Lava", 5}, {"Reason Stealer", 5}, {"Slime Creature, Medium", 5},
		{"Snowflake Ooze", 5}, {"Creeping Stone", 6}, {"Living Spell, Glitterfire", 6}, {"Ooze, Brine", 6},
		{"Pudding, White", 6}, {"Reekmurk", 6}, {"Shadow Jelly", 6}, {"Black Pudding", 7}, {"Bloodfire Ooze", 7},
		{"Conflagration Ooze", 7}, {"Living Spell, Cloudkill", 7}, {"Conflagration Ooze with Death Throes", 8},
		{"Void Ooze", 8}, {"Arcane Ooze", 9}, {"Corrupture", 9}, {"Living Spell, Chaos Blight", 9},
		{"Living Spell, Chilling Fog", 9}, {"Slime Creature, Large", 9}, {"Ethereal Ooze", 10},
		{"Black Pudding, Elder", 12}, {"Blighted Bloodfire", 12}, {"Infernal Conflagration Ooze", 13},
		{"Living Spell, Blasphemy", 13}, {"Living Spell, Dictum", 13}, {"Living Spell, Holy Word", 13},
		{"Living Spell, Word of Chaos", 13}, {"Infernal Conflagration Ooze with Death Throes", 14}, {"Nightseed", 14},
		{"Teratomorph", 16}, {"Flesh Jelly", 19}, {"Blood Ooze", 21}, {"Gelatinous Cube, Advanced", 24},
	},
	"Outsider": {
		{"Fiendish Familiar", 0}, {"Gutworm", 0}, {"Soul Tick", 0}, {"Aasimar", 0}, {"Air Gen", 0},
		{"Earth Gen", 0}, {"Fire Gen", 0}, {"Formian, Worker", 0}, {"Glimmerfok", 0}, {"Maeluth", 0},
		{"Mechanatrix", 0}, {"Mortif", 0}, {"Salamander, Flamebrother", 0}, {"Tiefling", 0}, {"Water Gen", 0},
		{"Wispling", 0}, {"Bladeling", 1}, {"Chaond", 1}, {"Demon, Mane", 1}, {"Devil, Lemure", 1},
		{"Ether Scarab", 1}, {"Kaorti", 1}, {"Nerra, Varoot", 1}, {"Salamander, Average Larva", 1},
		{"Shyft", 1}, {"Windrazor", 1}, {"Zenythri", 1}, {"Archon, Lantern", 2}, {"Azer", 2},
		{"Bacchae", 2}, {"Baphitaur", 2}, {"Demon, Abyssal Maw", 2}, {"Demon, Abyssal Skulker", 2},
		{"Demon, Dretch", 2}, {"Demon, Nashrou", 2}, {"Demon, Quasit", 2}, {"Demonhive Attendant", 2},
		{"Eladrin, Coure", 2}, {"Guardinal, Musteval", 2}, {"Hippogriff, Pseudo-Natural", 2}, {"Imp", 2},
		{"Lumi", 2}, {"Triton", 2}, {"Vargouille", 2}, {"Aoa, Droplet", 3}, {"Arrowhawk, Juvenile", 3},
		{"Bariaur", 3}, {"Demon, Rutterkin", 3}, {"Demon, Wrackspawn", 3}, {"Devil, Advespa", 3},
		{"Dusk Beast", 3}, {"Formian, Warrior", 3}, {"Guardinal, Cervidal", 3}, {"Half-Fiend Durzagon", 3},
		{"Hell Hound", 3}, {"Howler", 3}, {"Imp, Bloodbag", 3}, {"Imp, Choleric", 3}, {"Imp, Euphoric", 3},
		{"Imp, Filth", 3}, {"Imp, Melancholic", 3}, {"Imp, Phlegmatic", 3}, {"Imp, Sanguine", 3},
		{"Mephit, Air", 3}, {"Mephit, Dust", 3}, {"Mephit, Earth", 3}, {"Mephit, Fire", 3}, {"Mephit, Glass", 3},
		{"Mephit, Ice", 3}, {"Mephit, Magma", 3}, {"Mephit, Ooze", 3}, {"Mephit, Salt", 3}, {"Mephit, Steam", 3},
		{"Mephit, Sulfur", 3}, {"Mephit, Water", 3}, {"Nerra, Kalareem", 3}, {"Tojanida, Juvenile", 3},
		{"Xorn, Juvenile", 3}, {"Yeth Hound", 3}, {"Yugoloth, Skeroloth", 3}, {"Archon, Hound", 4},
		{"Barghest", 4}, {"Demon, Ekolid", 4}, {"Demon, Guecubu", 4}, {"Demon, Skulvyn", 4}, {"Demon, Vorr", 4},
		{"Devil, Spinagon", 4}, {"Energon, Xag-Ya", 4}, {"Giant Eagle, Radiant", 4}, {"Janni", 4},
		{"Nightmare, Lesser", 4}, {"Rainbow Dweller", 4}, {"Windscythe", 4}, {"Yugoloth, Voor", 4},
		{"Achaierai", 5}, {"Arrowhawk, Adult", 5}, {"Barghest, Greater", 5}, {"Canomorph, Haraknin", 5},
		{"Demon, Abyssal Ravager", 5}, {"Demon, Bar-Lgura", 5}, {"Demon, Jovoc", 5}, {"Demon, Nabassu, Juvenile", 5},
		{"Demon, Skurchur", 5}, {"Devil, Beared", 5}, {"Dwarf, Midgard", 5}, {"Energon, Xac-Yel", 5},
		{"Energon, Xac-Yij", 5}, {"Energon, Xap-Yaup", 5}, {"Energon, Xeg-Yi", 5}, {"Energon, Xong-Yong", 5},
		{"Energon, Xor-Yost", 5}, {"Genie, Djinni", 5}, {"Guardinal, Lupinal", 5}, {"Hordling", 5},
		{"Marrash", 5}, {"Mercane", 5}, {"Nightmare", 5}, {"Nightmare, Cauchemar", 5}, {"Rast", 5},
		{"Ravid", 5}, {"Rejkar", 5}, {"Shadow Mastiff", 5}, {"Slyph", 5}, {"Spellshadow", 5},
		{"Tojanida, Adult", 5}, {"Visilight", 5}, {"Yugoloth, Canoloth", 5}, {"Yugoloth, Corruptor of Fate", 5},
		{"Archon, Justice", 6}, {"Demon, Babau", 6}, {"Demon, Broodswarm", 6}, {"Demon, Uridezu", 6},
		{"Demonhive Queen", 6}, {"Devil, Desert", 6}, {"Dwarf Ancestor", 6}, {"Ebon Aspect", 6},
		{"Eladrin, Bralani", 6}, {"Formian, Winged Warrior", 6}, {"Genie, Qorrashi", 6}, {"Guardinal, Equinal", 6},
		{"Kyton", 6}, {"Malfera", 6}, {"Minotaur of Legend", 6}, {"Minotaur, Half-Earth Elemental", 6},
		{"Nerra, Sillit", 6}, {"Quori, Hashalaq", 6}, {"Salamander, Average", 6}, {"Slaad, Mud", 6},
		{"Thunder", 6}, {"Xill", 6}, {"Xorn, Adult", 6}, {"Yugoloth, Mezzoloth", 6}, {"Bezekira", 7},
		{"Chaos Beast", 7}, {"Demon, Armanite", 7}, {"Demon, Arrow", 7}, {"Demon, Colchiln", 7},
		{"Demon, Succubus", 7}, {"Devil, Amnizu", 7}, {"Formian, Taskmaster", 7}, {"Genie, Dao", 7},
		{"Keeper", 7}, {"Krathbairn", 7}, {"Lillend", 7}, {"Quori, Tsucora", 7}, {"Slaad, Red", 7},
		{"Slow Shadow", 7}, {"Archon, Warden", 8}, {"Arrowhawk, Elder", 8}, {"Asura", 8}, {"Demon, Ankshar", 8},
		{"Demon, Dybbuk", 8}, {"Demon, Palrethee", 8}, {"Demon, Yochlol", 8}, {"Devil, Erinyes", 8},
		{"Formian, Armadon", 8}, {"Genie, Djinni Noble", 8}, {"Genie, Efreeti", 8}, {"Glimmerskin", 8},
		{"Hob", 8}, {"Hollyphant-Winged Elephant", 8}, {"Hollyphant-Winged Mastodon", 8}, {"Rakshasa, Zakya", 8},
		{"Slaad, Blue", 8}, {"Trilloch", 8}, {"Xorn, Elder", 8}, {"Yugoloth, Echinoloth", 8}, {"Abyssal Drake", 9},
		{"Archon, Hammer", 9}, {"Aspect of Baphomet", 9}, {"Aspect of Zuggtmoy", 9}, {"Bonespider Swarm", 9},
		{"Canomorph, Vultivor", 9}, {"Demon, Bulezau", 9}, {"Demon, Maurezhi", 9}, {"Demon, Mavawhan", 9},
		{"Demon, Vrock", 9}, {"Demon, Whisper", 9}, {"Demon, Zovvut", 9}, {"Deva, Movanic", 9},
		{"Devil, Bone", 9}, {"Devil, Malebrache", 9}, {"Devil, Narzugon", 9}, {"Dune Stalker", 9},
		{"Ecalypse", 9}, {"Genie, Marid", 9}, {"Guardinal, Avoral", 9}, {"Nessian Warhound", 9},
		{"Night Hag", 9}, {"Rilmani, Ferrumach", 9}, {"Slaad, Green", 9}, {"Tojanida, Elder", 9},
		{"Unraveler", 9}, {"Vaporighu", 9}, {"Yugoloth, Piscoloth", 9}, {"Aspect of Kostchtchie", 10},
		{"Couatl", 10}, {"Demon, Chasme", 10}, {"Eladrin, Firre", 10}, {"Formian, Myrmarch", 10},
		{"Guardinal, Ursinal", 10}, {"Maelephant", 10}, {"Ogre Mage, Entropic", 10}, {"Rakshasa", 10},
		{"Salamander, Noble", 10}, {"Slaad, Gray", 10}, {"Sunfly Swarm", 10}, {"Yugoloth, Marraenoloth", 10},
		{"Yugoloth, Nycaloth", 10}, {"Yugoloth, Yagnoloth", 10}, {"Archon, Owl", 11}, {"Archon, Sword", 11},
		{"Asag", 11}, {"Bebilith, Loth-Touched", 11}, {"Canomorph, Shadurakul", 11}, {"Demodand, Farastu", 11},
		{"Demon, Hezrou", 11}, {"Demon, Kastighur", 11}, {"Devil, Barbed", 11}, {"Dire Tiger, Vivacious", 11},
		{"Formian, Observer", 11}, {"Hordling, Spittlemaw", 11}, {"Rakshasa, Naztharune", 11}, {"Astral Stalker", 12},
		{"Basilisk, Abyssal Greater", 12}, {"Demon, Lilitu", 12}, {"Demon, Vathugu", 12}, {"Deva, Monadic", 12},
		{"Devil, Stoney", 12}, {"Earth Glider", 12}, {"Ethereal Slayer", 12}, {"Guardinal, Leonal", 12},
		{"Moon Dog", 12}, {"Rilmani, Cuprilach", 12}, {"Demodand, Kelubar", 13}, {"Demon, Glabrezu", 13},
		{"Demon, Jarilith", 13}, {"Demon, Oculus", 13}, {"Devil, Ice", 13}, {"Eladrin, Ghaele", 13},
		{"Hellchain Weaver", 13}, {"Hordling, Dread Gnasher", 13}, {"Justicator", 13}, {"Kraken, Half-Fiend", 13},
		{"Scyllan", 13}, {"Slaad, Death", 13}, {"Steel Predator", 13}, {"Yugoloth, Ultroloth", 13},
		{"Archon, Trumpet", 14}, {"Demon, Alkilith", 14}, {"Demon, Nalfeshnee", 14}, {"Deva, Astral", 14},
		{"Eladrin, Shiradi", 14}, {"Rukarazyll", 14}, {"Aoa, Sphere", 15}, {"Archon, Throne", 15},
		{"Demon, Anzu", 15}, {"Demon, Nabassu, Mature", 15}, {"Demon, Sibriex", 15}, {"Hound of Kostchtchie", 15},
		{"Quori, Kalaraq", 15}, {"Rakshasa, Ak'chazar", 15}, {"Demodand, Shator", 16}, {"Demon, Goristro", 16},
		{"Devil, Horned", 16}, {"Hordling, Vultrewretch", 16}, {"Planetar", 16}, {"Astral Dreadnought", 17},
		{"Demon, Marilith", 17}, {"Demon, Sorrowsworn", 17}, {"Demon, Wastrilith", 17}, {"Formian, Queen", 17},
		{"Hordling, Skullreaver", 17}, {"Rilmani, Aurumach", 17}, {"Yugoloth, Arcanaloth", 17}, {"Demon, Deathdrinker", 18},
		{"Demon, Kelvezu", 18}, {"Devil, Xerfilstyx", 18}, {"Eladrin, Tulani", 18}, {"Concordant Killer", 19},
		{"Demon, Molydeus", 19}, {"Marruspawn Abomination", 19}, {"Broodfiend", 20}, {"Daelkyr", 20},
		{"Demon, Balor", 20}, {"Devil, Pit Fiend", 20}, {"Demon, Myrmyxicus", 21}, {"Titan", 21},
		{"Devil, Paeliryon", 22}, {"Solar", 23}, {"Demon, Klurichir", 25},
	},
	"Plant": {
		{"Twig Blight", 0}, {"Myconid, Junior Worker", 0}, {"Yellow Musk Zombie Orc", 0}, {"Myconid, Average Worker", 1},
		{"Shrieker", 1}, {"Dusanu", 2}, {"Myconid, Elder Worker", 2}, {"Needlefolk", 2}, {"Wizended Elder", 2},
		{"Assassin Vine", 3}, {"Bloodthorn", 3}, {"Phantom Fungus", 3}, {"Phycomid", 3}, {"Topiary Guardian, Boar", 3},
		{"Tumbling Mound", 3}, {"Violet Fungus", 3}, {"Wortling", 3}, {"Dusanu, Advanced", 4},
		{"Myconid, Guard", 4}, {"Vine Horror", 4}, {"Wood Woad", 4}, {"Yellow Musk Creeper", 4},
		{"Death's Head Tree", 5}, {"Basidirond", 5}, {"Briarvex", 6}, {"Dread Blossom Swarm", 6},
		{"Ironthorn", 6}, {"Myconid, Circle Leader", 6}, {"Shambling Mound", 6}, {"Tendriculos", 6},
		{"Battlebriar, Lesser", 7}, {"Myconid, Sovereign", 7}, {"Topiary Guardian, Lion", 7}, {"Treant", 8},
		{"Kelp Angler", 9}, {"Saguaro Sentiel", 9}, {"Greenvice", 10}, {"Sporebat", 10}, {"Umbral Banyan", 10},
		{"Night Twist", 12}, {"Oaken Defender", 12}, {"Octopus Tree", 12}, {"Topiary Guardian, Triceratops", 12},
		{"Ironmaw", 13}, {"Red Sundew", 13}, {"Battlebriar", 15}, {"Plague Brush", 17},
		{"Night Twist, Ancient", 20}, {"Orcwort", 20}, {"Octopus Tree, Advanced", 26},
	},
	"Undead": {
		{"Skeleton, Dire Rat", 0}, {"Skeleton, Halfling Warrior", 0}, {"Skeleton, Human Warrior", 0},
		{"Skeleton, Kobold Warrior", 0}, {"Zombie, Dire Rat", 0}, {"Zombie, Gnome Warrior", 0},
		{"Zombie, Goblin Warrior", 0}, {"Zombie, Human Commoner", 0}, {"Zombie, Kobold", 0},
		{"Ghoul", 1}, {"Kyuss Spawnling", 1}, {"Lacedon", 1}, {"Raiment", 1}, {"Skeleton, Crocodile", 1},
		{"Skeleton, Dire Badger", 1}, {"Skeleton, Gnoll Warrior", 1}, {"Skeleton, Wolf", 1}, {"Zombie, Gnoll Warrior", 1},
		{"Zombie, Skum", 1}, {"Zombie, Troglodyte", 1}, {"Zombie, Wolf", 1}, {"Desiccator", 2},
		{"Ghostly Visage", 2}, {"Ghoul, Fleshvigor", 2}, {"Skeleton, Deinonychus", 2}, {"Skeleton, Heavy Warhorse", 2},
		{"Skeleton, Ogre", 2}, {"Skeleton, Owlbear", 2}, {"Slaymate", 2}, {"Tomb Mote", 2}, {"Vasuthant", 2},
		{"Zombie, Black Bear", 2}, {"Zombie, Bugbear", 2}, {"Zombie, Werewolf", 2}, {"Allip", 3}, {"Ashen Husk", 3},
		{"Bone Rat Swarm", 3}, {"Crypt Thing", 3}, {"Deathlock", 3}, {"Dreamstealer Spawn", 3}, {"Ghast", 3},
		{"Ghost Brute Hound", 3}, {"Ghoul True", 3}, {"Mastiff of Kyuss", 3}, {"Murk", 3}, {"Necrosis Carnex", 3},
		{"Plague Walker", 3}, {"Quell", 3}, {"Shadow", 3}, {"Skeleton, Brown Bear", 3}, {"Skeleton, Karnathi", 3},
		{"Skeleton, Minotaur", 3}, {"Skeleton, Troll", 3}, {"Skin Kite", 3}, {"Zombie, Centaur", 3},
		{"Zombie, Dire Ape", 3}, {"Zombie, Karrnathi", 3}, {"Zombie, Ogre", 3}, {"Blackskate", 4},
		{"Bloodhulk Fighter", 4}, {"Bonedrinker, Lesser", 4}, {"Brain in a Jar", 4}, {"Corpse Rat Swarm", 4},
		{"Forlorn Husk", 4}, {"Ghast, Spellstitched", 4}, {"Living Wall-Human", 4}, {"Nether Hound Ghast", 4},
		{"Skeleton, Chimera", 4}, {"Skeleton, Hydra, 9 Headed", 4}, {"Skulking Cyst", 4}, {"Spectral Lyrist", 4},
		{"Steaming Soldier", 4}, {"Vampire Spawn", 4}, {"Web Mummy", 4}, {"Wight", 4}, {"Zombie, Hound Archon", 4},
		{"Zombie, Hydra, 5 Headed", 4}, {"Zombie, Minotaur", 4}, {"Zombie, Wyvern", 4}, {"Boneclaw", 5},
		{"Dreamstealer", 5}, {"Drowned One", 5}, {"Entomber", 5}, {"Ephemeral Swarm", 5}, {"Felldrake, Spectral", 5},
		{"Ghost, Frostfell", 5}, {"Icy Prisoner", 5}, {"Mummy", 5}, {"Necropolitan", 5}, {"Ogre, Mummified", 5},
		{"Skeleton, Elephant", 5}, {"Skeleton, Ettin", 5}, {"Spawn of Kyuss", 5}, {"Wraith", 5},
		{"Zombie Young Adult White Dragon", 5}, {"Zombie, Megaraptor", 5}, {"Zombie, Umber Hulk", 5},
		{"Bloodhulk Giant", 6}, {"Bloodmote Cloud", 6}, {"Bonedrinker", 6}, {"Cinderspawn", 6}, {"Defacer", 6},
		{"Displacer Beast, Umbral", 6}, {"Forsaken Shell", 6}, {"Icegaunt", 6}, {"Living Wall-Manticore", 6},
		{"Necromental, Large Earth", 6}, {"Plague Blight", 6}, {"Skeleton, Advanced Megaraptor", 6},
		{"Skeleton, Athach", 6}, {"Skeleton, Dire Bear", 6}, {"Skeleton, Glabrezu", 6}, {"Voidwraith", 6},
		{"Wraith, Evolved", 6}, {"Zombie, Behir", 6}, {"Zombie, Gray Render", 6}, {"Zombie, Vrock", 6},
		{"Bleakborn", 7}, {"Crypt Changer", 7}, {"Death Scarab Swarm", 7}, {"Dust Wight", 7}, {"Ghost, Human Fighter", 7},
		{"Gravetouched Ghoul", 7}, {"Huecuva", 7}, {"Living Wall-Elf Sorcerer", 7}, {"Quth-Maren", 7},
		{"Skeletal Mature Adult Black Dragon", 7}, {"Skeleton, Cloud Giant", 7}, {"Skirr", 7}, {"Spectre", 7},
		{"Swordwraith", 7}, {"Vampire, Human Fighter", 7}, {"Zombie, Giant Squid", 7}, {"All-Consuming Hunger", 8},
		{"Animus Human Cleric", 8}, {"Bloodhulk Crusher", 8}, {"Bodak", 8}, {"Crawling Slaughter", 8}, {"Mohrg", 8},
		{"Salt Mummy", 8}, {"Shadow, Greater", 8}, {"Shoosuva", 8}, {"Skeleton, Roc", 8}, {"Skeleton, Storm Giant", 8},
		{"Skeleton, Tyrannosaurus", 8}, {"Skeleton, Young Adult Red Dragon", 8}, {"Slaughter Wight", 8},
		{"Bhut", 9}, {"Blaspheme", 9}, {"Blood Amniote", 9}, {"Drowned", 9}, {"Hulking Corpse", 9}, {"Visage", 9},
		{"Winterspawn", 9}, {"Abyssal Ghoul", 10}, {"Entombed", 10}, {"Eviscerator Beetle", 10}, {"Plague Spewer", 10},
		{"Revived Fossil Magaraptor", 10}, {"Sword of Kyuss", 10}, {"Wormcaller", 10}, {"Zombie, Dire Shark", 10},
		{"Zombie, Plesiosaur", 10}, {"Atropal Scion", 11}, {"Crawling Apocalypse", 11}, {"Crimson Death", 11},
		{"Devourer", 11}, {"Dread Wraith", 11}, {"Grimweird", 11}, {"Naga, Bone", 11}, {"Ulgurstasta", 11},
		{"Vitreous Drinker", 11}, {"Weep", 11}, {"Entropic Reaper", 12}, {"Charnel Hound", 13}, {"Death Knight", 13},
		{"Earthcander Centipede", 13}, {"Eldritch Archer", 13}, {"Kyuss Knight", 13}, {"Lich, Human Wizard", 13},
		{"Blood Fiend", 14}, {"Boneyard", 14}, {"Ghostly Adult Green Dragon", 14}, {"Necronaut", 14}, {"Nightwing", 14},
		{"Angel of Decay", 15}, {"Deathshrieker", 15}, {"Elite Vampire", 15}, {"Hullathoin", 15}, {"Humbaba", 15},
		{"Kraken, Corpse Creature", 15}, {"Mummy Lord", 15}, {"Acidwraith", 16}, {"Dream Vestige", 16},
		{"Gravecrawler", 16}, {"Jahi", 16}, {"Nightwalker", 16}, {"Swarm-Shifter, Mummy King", 16},
		{"Banshee", 17}, {"Deathbringer", 17}, {"Effigy", 17}, {"Suel Lich", 17}, {"Vasuthant, Horrific", 17},
		{"Dry Lich", 18}, {"Mindkiller Scorpion", 18}, {"Nightcrawler", 18}, {"Corpse Gatherer", 19},
		{"Deathshrieker, Advanced", 19}, {"Famine Spirit", 19}, {"Ragewind", 19}, {"Crawling Head", 20},
		{"Vampiric Mature Adult Red Dragon", 20}, {"Dracolich, Ancient Blue", 23},
	},
	"Vermin": {
		{"Monstrous Centipede, Tiny", 0}, {"Hurrum, Speckled", 0}, {"Mulworm", 0}, {"Monstrous Centipede, Small", 0},
		{"Monstrous Diving Spider, Tiny", 0}, {"Monstrous Scorpion, Tiny", 0}, {"Monstrous Spider, Tiny", 0},
		{"Fire Beetle, Giant", 0}, {"Giant Termite, Worker", 0}, {"Leech, Giant", 0}, {"Hoard Scarab", 0},
		{"Maggot, Giant", 0}, {"Monstrous Centipede, Medium", 0}, {"Monstrous Crab, Small", 0},
		{"Monstrous Diving Spider, Small", 0}, {"Monstrous Scorpion, Small", 0}, {"Monstrous Snow Spider, Small", 0},
		{"Monstrous Spider, Small", 0}, {"Acid Beetle Swarm", 1}, {"Giant Ant, Worker", 1}, {"Giant Bee", 1},
		{"Giant Termite, Queen", 1}, {"Leech Swarn", 1}, {"Monstrous Centipede, Large", 1},
		{"Monstrous Diving Spider, Medium", 1}, {"Monstrous Scorpion, Medium", 1}, {"Monstrous Snow Spider, Medium", 1},
		{"Monstrous Spider, Medium", 1}, {"Mummy Mites", 1}, {"Spider Swarm", 1}, {"Cockroach, Giant", 2},
		{"Dire Maggot", 2}, {"Giant Ant, Queen", 2}, {"Giant Ant, Soldier", 2}, {"Giant Beetle, Bombardier", 2},
		{"Giant Termite, Soldier", 2}, {"Monstrous Centipede, Huge", 2}, {"Monstrous Crab, Medium", 2},
		{"Monstrous Diving Spider, Large", 2}, {"Monstrous Snow Spider, Large", 2}, {"Monstrous Spider, Large", 2},
		{"Tick, Giant", 2}, {"Wasp Swarm", 2}, {"Brine Swimmer", 3}, {"Crayfight, Giant", 3},
		{"Giant Praying Mantis", 3}, {"Giant Wasp", 3}, {"Locust Swarm", 3}, {"Monstrous Hunting Spider, Large", 3},
		{"Monstrous Scorpion, Large", 3}, {"Centipede Swarm", 4}, {"Giant Beetle, Stag", 4}, {"Monstrous Crab, Large", 4},
		{"Giant Ant Lion", 5}, {"Hoard Scarab Swarm", 5}, {"Jellyfish Swarm", 5}, {"Knell Beetle, Lesser", 5},
		{"Monstrous Diving Spider, Huge", 5}, {"Monstrous Spider, Huge", 5}, {"Plague Ant Swarm", 5},
		{"Scorpion Swarm", 5}, {"Swamp Strider Swarm", 5}, {"Chelicera", 6}, {"Locust Swarm, Rapture", 6},
		{"Monstrous Centipede, Gargantuan", 6}, {"Neogi, Great Old Master", 6}, {"Jungle Spider", 7},
		{"Monstrous Crab, Huge", 7}, {"Monstrous Scorpion, Huge", 7}, {"Locust Swarm, Bloodfiend", 8},
		{"Monstrous Diving Spider, Gargantuan", 8}, {"Monstrous Spider, Gargantuan", 8},
		{"Monstrous Centipede, Colossal", 9}, {"Hastendeath Spider Swarm", 10}, {"Knell Beetle", 10},
		{"Leechwalker", 10}, {"Monstrous Crab, Gargantuan", 10}, {"Monstrous Scorpion, Gargantuan", 10},
		{"Scarab Beetle Swarm", 10}, {"Wormswarm", 10}, {"Monstrous Diving Spider, Colossal", 11},
		{"Monstrous Spider, Colossal", 11}, {"Bonespear", 12}, {"Monstrous Scorpion, Colossal", 12},
		{"Monstrous Crab, Colossal", 13}, {"Siege Crab", 14}, {"Kraken, Astral", 16}, {"Siege Crab, Greater", 18},
		{"Century Worm", 19}, {"Megapede", 20}, {"Ruin Swarm", 23},
	},
}

func getEncounterData(mType string, apl int) (string, int) {
	if apl < 1 {
		apl = 1
	}

	list, exists := monsterDatabase[mType]
	if !exists || len(list) == 0 {
		return "Dire Rat", 1
	}

	var valid []MonsterData
	for _, m := range list {
		if m.CR <= apl {
			valid = append(valid, m)
		}
	}

	if len(valid) == 0 {
		return list[0].Name, list[0].CR
	}

	maxValidCR := 0
	for _, m := range valid {
		if m.CR > maxValidCR {
			maxValidCR = m.CR
		}
	}

	var challenging []MonsterData
	for _, m := range valid {
		if m.CR >= maxValidCR-3 {
			challenging = append(challenging, m)
		}
	}

	choice := challenging[rand.Intn(len(challenging))]
	return choice.Name, choice.CR
}

func generateEncounter(mType string, apl int) Monster {
	if apl < 1 {
		apl = 1
	}

	name, actualCR := getEncounterData(mType, apl)

	count := 1
	crDiff := apl - actualCR

	if crDiff >= 8 {
		count = 12
	} else if crDiff >= 6 {
		count = 8
	} else if crDiff >= 4 {
		count = 4
	} else if crDiff >= 2 {
		count = 2
	}

	return Monster{
		Name:  name,
		Type:  mType,
		Count: count,
		CR:    actualCR,
	}
}

func (m *Map) PlaceMonsters() {
	for i := range m.Rooms {
		spawnChance := 40
		if m.Rooms[i].IsFocal {
			spawnChance = 100
		}

		if rand.Intn(100) < spawnChance {
			mType := getMonsterCategoryForRoom(m.Rooms[i].RType, m.Theme.Environment)
			encounter := generateEncounter(mType, m.Config.APL)
			m.Rooms[i].Monsters = append(m.Rooms[i].Monsters, encounter)
		}
	}
}
